Backend documentation update
cambiatus/backend pull request #105
Opened 2020-10-29 17:44 UTC by victorgdev

## What issue does this PR close
Closes #92 

## Changes Proposed ( a list of new changes introduced by this PR)
Updates backend documentation

2020-10-29 17:46 UTC, victorgdev commented
@amiskov & @lucca65 this documentation PR created and is a work in progress. Can you guys give me some structure of content and content feedback! Thanks in advance!

2020-10-29 20:45 UTC, lucca65 approved these changes

2020-10-30 20:00 UTC, amiskov requested changes
I wish I was reading this last spring when I started working with Cambiatus 👍

2020-11-02 19:16 UTC, victorgdev commented
@lucca65 & @amiskov  I think we got a good publishable version for our backend documentation and [wiki onboarding](https://github.com/cambiatus/cambiatus.github.io/pull/2). Let me know what you guys think! 💪

2020-11-03 15:52 UTC, lucca65 requested changes
Overall good, just some points here and there, I really didn't get the bold titles, AFAIK they don't change

2020-11-03 15:52 UTC, lucca65 commented on README.md
> +## **Dataflow**
Isn't Bold on title irrelevant?

```suggestion
## Dataflow
```

2020-11-03 15:52 UTC, lucca65 commented on README.md
> +## **General Information**
I think adding bold on title is irrelevant, the final render is the same, isn't it?
```suggestion
## General Information
```

2020-11-03 15:52 UTC, lucca65 commented on README.md
>  Welcome to the Application that serves as one of the backends for the Cambiatus Ecosystem, One of the backends since this is the one that contains the data in a manner than is easy to index and searc
Do we have multiple backends? I know its not related to this PR, but still 🤔

2020-11-03 15:52 UTC, lucca65 commented on README.md
> +- [Absinthe package](https://hexdocs.pm/absinthe/overview.html) GraphQL toolkit for Elixir
Ecto isn't a query language, maybe we have have a section of "notable packages" or something similar

2020-11-03 15:52 UTC, lucca65 commented on README.md
> +**Database dumping**
Database dumping can be on the wiki, added to the onboarding section

2020-11-03 15:52 UTC, lucca65 commented on README.md
> +      - ONLY revert the changes related to the local database connection credentials on these two files (`dev.exs` and `text.exs`).
Although this process is ok, developers can use `exclude`

https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-some-files-locally

2020-11-03 18:16 UTC, victorgdev commented on README.md
> +**Database dumping**
Ok will move it over!

2020-11-03 18:17 UTC, victorgdev commented on README.md
> +      - ONLY revert the changes related to the local database connection credentials on these two files (`dev.exs` and `text.exs`).
Should I add as an alternative or as default recommendation?

2020-11-03 18:18 UTC, victorgdev commented on README.md
> +- [Absinthe package](https://hexdocs.pm/absinthe/overview.html) GraphQL toolkit for Elixir
I like the notable packages idea

2020-11-03 18:19 UTC, lucca65 commented on README.md
> +      - ONLY revert the changes related to the local database connection credentials on these two files (`dev.exs` and `text.exs`).
I think it can be an alternative, handling what you stage on git is the most basic process

2020-11-03 18:27 UTC, victorgdev commented on README.md
>  Welcome to the Application that serves as one of the backends for the Cambiatus Ecosystem, One of the backends since this is the one that contains the data in a manner than is easy to index and searc
This paragraph was copied from the original and I had put it on my notes to ask about it on our next dev meeting. Because it got me a bit confused as well. 

My guess is that by Cambiatus Ecosystem it is meant that multiple applications exist and this backend repo represents one of the backend application that serve one of these applications (part of the Cambiatus ecosystem).

2020-11-05 23:54 UTC, lucca65 commented on README.md
>  Welcome to the Application that serves as one of the backends for the Cambiatus Ecosystem, One of the backends since this is the one that contains the data in a manner than is easy to index and searc
I guess the problem is related to "backends", might be misleading because the context here is to talk about a repo with the same name. I think from where it was extracted it might make sense, but it might be confusing

2020-11-09 14:52 UTC, lucca65 approved these changes

2020-11-12 11:50 UTC, amiskov approved these changes
Nice!

2020-11-12 15:27 UTC, amiskov requested changes

2020-11-12 15:27 UTC, amiskov commented on README.md
> +
@victorgdev @lucca65  Sorry, I forgot on important detail!

We also need [ImageMagick](https://imagemagick.org/) installed in the system to upload images properly. Otherwise, the server will run but there will be errors in any image uploading. Some instructions on how to install ImageMagick could be found [here](https://imagemagick.org/script/download.php).

I think it's fine to have this description right here, in Section 3, before `mix deps.get` since ImageMagic will be used by [one](https://hex.pm/packages/mogrify) of the dependencies.

2020-11-12 16:05 UTC, lucca65 commented on README.md
> +
+1, build failed for me in prod a few days ago!

2020-11-13 14:07 UTC, amiskov approved these changes

2020-11-13 14:08 UTC, merged