Fix link to EOS in Readme file
cambiatus/backend pull request #117
Opened 2020-11-30 20:51 UTC by vitorleal

## What issue does this PR close
Closes #116 

## Changes Proposed ( a list of new changes introduced by this PR)
 - Update the link of EOS to the correct one

2020-12-04 16:56 UTC, lucca65 requested changes

2020-12-04 18:31 UTC, vitorleal commented
Oh, perfect. Updated.

Cheers

2020-12-05 13:56 UTC, lucca65 approved these changes

2020-12-05 13:56 UTC, lucca65 commented
Thanks for the contribution 🙌

2020-12-05 13:56 UTC, merged