Fix/fix phone regex
cambiatus/backend pull request #131
Opened 2021-02-28 21:17 UTC by venomnert

## What issue does this PR close

Closes #128 

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Introduced a standard way to verify brazil phone numbers
- [ ] Updated telegram and instagram username regex
- [ ] Included test coverage for contacts

## How to test ( a list of instructions on how to test this PR)

- [ ] Run `mix test`. Ensure all test pass
- [ ] Create a contact info of `phone` type and update it `whatsapp`.
- [ ] Try entering invalid telegram and instagram ids.

Ensure to put focus on user's contact creation.

2021-03-01 12:08 UTC, lucca65 requested changes

2021-03-01 12:08 UTC, lucca65 commented on lib/cambiatus/accounts/contact.ex
> +    {:ok, phone_number} = ExPhoneNumber.parse(external_id, country_code)
this way we are always checking the number as a US number, maybe we can try to pattern match / regex match the prefix to get the number? maybe expect always a `(\+){1}\d{2}` for the prefix

2021-03-01 12:08 UTC, lucca65 commented on lib/cambiatus/accounts/contact.ex
> +    case ExPhoneNumber.is_possible_number?(phone_number) do
I really think cases of true/false should be `if`s

2021-03-01 12:34 UTC, NeoVier commented on lib/cambiatus/accounts/contact.ex
> +    {:ok, phone_number} = ExPhoneNumber.parse(external_id, country_code)
shouldn't the prefix be `\+?\d{1,3}`? There are country codes that are 1 digit long (US), 2 digits long (BR), and 3 digits long (CR)

2021-03-01 12:35 UTC, lucca65 commented on lib/cambiatus/accounts/contact.ex
> +    {:ok, phone_number} = ExPhoneNumber.parse(external_id, country_code)
+1 but the `+` shouldn't be optional

2021-03-01 13:41 UTC, venomnert commented on lib/cambiatus/accounts/contact.ex
> +    {:ok, phone_number} = ExPhoneNumber.parse(external_id, country_code)
I believe the library can automatically detect phone number and its country. In that case we probably won't need regex.

I need to dig more into this.

2021-03-02 01:29 UTC, venomnert commented on lib/cambiatus/accounts/contact.ex
> +    case ExPhoneNumber.is_possible_number?(phone_number) do
I have made the update @lucca65

2021-03-02 01:32 UTC, venomnert commented on lib/cambiatus/accounts/contact.ex
> +    {:ok, phone_number} = ExPhoneNumber.parse(external_id, country_code)
Even though I set the default country code `BR` the library parses and recognizes all valid countries. The current implementation recognizes CR, US and BR and other countries, so no change is required.

2021-03-02 11:29 UTC, lucca65 approved these changes

2021-03-02 11:29 UTC, lucca65 commented on lib/cambiatus/accounts/contact.ex
> +    case changeset.changes.type do
uh I didn't knew about this! nice!

2021-03-02 11:29 UTC, lucca65 commented on lib/cambiatus/accounts/contact.ex
> +    {:ok, phone_number} = ExPhoneNumber.parse(external_id, country_code)
oh I see! nice!

2021-03-02 14:01 UTC, merged

2021-03-02 14:02 UTC, venomnert commented
- Resolved regex for social media users
- Standardized international phone number validation