Session table
cambiatus/backend pull request #140
Opened 2021-04-06 01:32 UTC by venomnert

## What issue does this PR close
Closes #138 

## Changes Proposed ( a list of new changes introduced by this PR)
* Utilize session table to stores information during sign in process: phrase, token, account, app version, etc... 

## How to test ( a list of instructions on how to test this PR)
1. `mix test`
2. Run the following queries: `startAuthSession`, `signInV2`, `signOut`

2021-04-06 21:11 UTC, lucca65 requested changes

2021-04-06 21:11 UTC, lucca65 commented on lib/cambiatus/auth/auth.ex
> +  def create_auth(user) do
maybe `create_phrase` because its what the function return?

2021-04-06 21:11 UTC, lucca65 commented on lib/cambiatus/auth/auth.ex
> +          |> case do
in those cases we can use `if`, pattern matching booleans 🤔

2021-04-06 21:11 UTC, lucca65 commented on lib/cambiatus_web/schema/account_types.ex
> +      resolve(&AccountsResolver.sign_out/3)
This should be an `arg`less mutation, and it should be authenticated. The way its described, looks like anyone can signOut a given `account`, if its a authenticated API call, then we already will have the user on the context

2021-04-06 21:11 UTC, lucca65 commented on lib/cambiatus_web/schema/account_types.ex
> +    field :start_auth_session, :auth_session do
just a suggestion, I'm not 100% confident about this, but maybe `generate_auth` or `gen_auth`, or `init_session` `generate_session`, etc

2021-04-08 23:59 UTC, venomnert commented on lib/cambiatus/auth/auth.ex
> +  def create_auth(user) do
I have made the udpate

2021-04-09 00:06 UTC, venomnert commented on lib/cambiatus/auth/auth.ex
> +          |> case do
Agreed and made the update. I will need to ensure to follow this pattern for future changes.

2021-04-09 00:07 UTC, venomnert commented on lib/cambiatus_web/schema/account_types.ex
> +      resolve(&AccountsResolver.sign_out/3)
That make sense. I have updated it so only the authorized user can logout.

2021-04-09 00:07 UTC, venomnert commented on lib/cambiatus_web/schema/account_types.ex
> +    field :start_auth_session, :auth_session do
Updated to `gen_auth`

2021-04-14 20:39 UTC, lucca65 commented on lib/cambiatus_web/resolvers/commune.ex
> +      end
is your branch updated with master?

2021-04-14 23:34 UTC, venomnert commented on lib/cambiatus_web/resolvers/commune.ex
> +      end
It is. Am i missing something?

2021-04-14 23:54 UTC, lucca65 commented on lib/cambiatus_web/resolvers/commune.ex
> +      end
but did you added this? the claim ordering was released here: https://github.com/cambiatus/backend/pull/139/files and here:https://github.com/cambiatus/backend/pull/136/files

2021-04-15 00:39 UTC, venomnert commented on lib/cambiatus_web/resolvers/commune.ex
> +      end
I believe the update has been made now.

2021-04-15 01:48 UTC, lucca65 requested changes
Good! we are on the right direction! I'm missing the tests attesting the new signUp and signIn flow from end to end

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/auth.ex
> +      select: [:context, :user_id, :token]
those two lines get repeated a lot, why not move it to UserToken module so the code get less repetitive, functions like `by_account` or `by_token`, etc.

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.verify(signature, phrase, pub_key)
didn't this triggered credo? 

if you are on a pipe you need to start with a raw value:

signature
|> Eosjs.verify(phrase)
|> case do

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +  end
is this really needed?

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.gen_rand_signature(phrase)
same here, if the objetive is to have less lengthy words you can use aliases

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.gen_rand_signature(phrase)
alias are useful:

```elixir
alias Foo.Bar, as: Bar
```

and in the case the problem is that the function is not descriptive enough, you can rename it on the package

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +  defp get_pub_key(account) do
not sure about this function returning nil bro, do you think we can improve it somehow?

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.gen_rand_signature(phrase)
also can you send a little explanation on the motivation behind random?

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/auth/user_token.ex
> +  @optional_fields ~w(phrase)a
maybe a blank line between those would be nice!

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus/commune/commune.ex
> +        (is_nil(a.deadline) or fragment("NOW()") < a.deadline) and
I'm confused about those lines, did you added them?

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus_web/resolvers/accounts.ex
> +      error -> error
this will match anything, maybe you want to 

```
else
  {:error, details} = error -> error
end

2021-04-15 01:48 UTC, lucca65 commented on lib/cambiatus_web/resolvers/commune.ex
> +      end
yeah did you wrote those lines? they look from the PR we did a while a go

2021-04-15 01:48 UTC, lucca65 commented on mix.exs
> -      {:nodejs, "~> 2.0"},
phew 🌶️

2021-04-15 01:52 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.verify(signature, phrase, pub_key)
credo should be ruined automatically by GitHub, but you can always run `mix credo`! 💪

2021-04-15 01:53 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +  defp get_pub_key(account) do
also, private functions usually don't bring much benefit if you are not working on a library

2021-04-15 01:53 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +  defp get_pub_key(account) do
the main reason why I don't like to use private functions is that you loose stack trace if you run into an error on them

2021-04-19 12:53 UTC, venomnert commented on lib/cambiatus_web/resolvers/accounts.ex
> +      error -> error
Made the update

2021-04-19 12:53 UTC, venomnert commented on lib/cambiatus/auth/user_token.ex
> +  @optional_fields ~w(phrase)a
Made the necessary format

2021-04-19 17:04 UTC, venomnert commented on lib/cambiatus/auth/auth.ex
> +      select: [:context, :user_id, :token]
I have extracted this into it's own module `Auth.Session`

2021-04-19 17:21 UTC, venomnert commented on lib/cambiatus_web/resolvers/commune.ex
> +      end
As discussed on our call this branch will update the main feature branch `improve-auth`.

2021-04-19 17:21 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.verify(signature, phrase, pub_key)
I have made the update

2021-04-19 17:21 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +  end
This used to for testing the auth process

2021-04-19 17:22 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.gen_rand_signature(phrase)
> same here, if the objetive is to have less lengthy words you can use aliases
Fixed this by utilizing alias

> also can you send a little explanation on the motivation behind random?
This function is utilized to test invalid signatures

2021-04-19 17:24 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +  defp get_pub_key(account) do
> not sure about this function returning nil bro, do you think we can improve it somehow?

I have made the fix for this

> the main reason why I don't like to use private functions is that you loose stack trace if you run into an error on them

I agree but the question I have is, how do we utilize helper functions in modules without polluting the api?

2021-04-19 17:25 UTC, venomnert commented on lib/cambiatus/commune/commune.ex
> +        (is_nil(a.deadline) or fragment("NOW()") < a.deadline) and
As discussed on our call this branch will update the main feature branch improve-auth.

2021-04-19 17:40 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +  end
why not simply call `EosjsAuthWrapper.sign(signature, priv_key)`directly in the test too?

2021-04-19 17:41 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.gen_rand_signature(phrase)
Still think that we can call `EosjsAuthWrapper` directly here, functions that alias other functions is just weird, adds a layer on something without any benefits

2021-04-19 17:42 UTC, lucca65 commented on lib/cambiatus/auth/ecdsa.ex
> +  defp get_pub_key(account) do
but how `defp` helps in avoiding said pollution?

2021-04-19 23:51 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +  end
I have made the update

2021-04-19 23:51 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +    EosjsAuthWrapper.gen_rand_signature(phrase)
Agreed, I made the necessary update.

2021-04-20 00:45 UTC, venomnert commented on lib/cambiatus/auth/ecdsa.ex
> +  defp get_pub_key(account) do
In my opinion private functions help hide the implementation details for the main functions of the module. In this case `get_pub_key` is a helper functions and it shouldn't be called outside off this module.

2021-04-21 00:29 UTC, lucca65 approved these changes

2021-04-21 00:29 UTC, lucca65 commented on .tool-versions
> +elixir 1.10.3-otp-23
this is weird, master is on 1.8, we have a PR to update it to 1.11

now yours is a different version too

2021-04-21 00:30 UTC, lucca65 commented
We can do a more complete review when we are finally targeting `master`

2021-04-21 01:36 UTC, venomnert commented on .tool-versions
> +elixir 1.10.3-otp-23
Hey @lucca65 as discussed here https://github.com/cambiatus/backend/issues/127. This will get merged in after we update Elixir.

2021-04-21 16:01 UTC, venomnert commented
Hey @lucca65 I just added 1 more update.

I added extra tests to covers signup -> signout process

2021-04-21 17:04 UTC, lucca65 approved these changes
Looks good! ✨

2021-04-22 10:41 UTC, merged