Multi sessions
cambiatus/backend pull request #150
Opened 2021-04-23 13:23 UTC by venomnert

## What issue does this PR close
Closes #141 

## Changes Proposed ( a list of new changes introduced by this PR)
* This allows a single user to sign in from multiple devices

## How to test ( a list of instructions on how to test this PR)
1. `mix test`

2021-04-23 16:10 UTC, lucca65 requested changes
Little confused about the absinthe context changes, are they really needed?

Also the query functions could be much improved.

I've noticed as well some formatting issues, please make sure to configure your editor to auto format for you! it will make everything easier!

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus/auth/session.ex
> +  end
is this function really needed? can't we simply call it directly?

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus/auth/session.ex
> +  end
is this function really needed? can't we simply call it directly?

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus/auth/session.ex
> +    |> Repo.one()
all those functions are getting repetitive, maybe we can use something like we do on Claim or Product with functions that are composed to create queries, like UserToken.withContext() instead of writing that where several times in the same module

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus/auth/sign_up.ex
> +  def sign_up(params, :bypass_eos) do
bypass_eos?

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus/auth/user_token.ex
> +end
this module could be improved with functions that build queries, check Product and Claim

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus/commune/commune.ex
> +        (is_nil(a.deadline) or fragment("NOW()") < a.deadline) and
this again 😫😫😫

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus_web/before_send.ex
> +    end
can you document/explain this function a little better? why do we need it?

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus_web/plugs/set_current_user.ex
> +         %User{} = user <- Auth.verify(token) do
oh now I see verify now returns an user, maybe for separation of concerns we could simply let auth verify it, we can grab the user later as it is not required for the auth process, this makes our code more modular and the function names more explicit and easy to grasp

2021-04-23 16:10 UTC, lucca65 commented on lib/cambiatus_web/plugs/set_phrase.ex
> +    context = conn |> get_phrase() |> set_user_agent() |> update_context()
why the phrase needs to be on the context? is it needed?

2021-04-25 16:16 UTC, venomnert reviewed
Hey @lucca65 what was the decision we made on our weekly call?
* Option 1: Continue to utilize this functionality. Which in turn would reduce the extra information passed by frontend on sign in, `account`. If we are going to use this functionality then I will refactor the documentation.

* Option 2: If you don't want us to use this approach, frontend would have to send `signature` & `account` on sign in. Then I will refactor accordingly.

2021-04-25 16:17 UTC, venomnert commented on lib/cambiatus/auth/session.ex
> +    |> Repo.one()
Made the update. Definitely helped to reduce the code and improve readability.

2021-04-25 16:17 UTC, venomnert commented on lib/cambiatus/auth/session.ex
> +  end
Removed this function

2021-04-25 16:18 UTC, venomnert commented on lib/cambiatus_web/before_send.ex
> +    end
Hey @lucca65 what was the decision we made on our weekly call?

Option 1: Continue to utilize this functionality. Which in turn would reduce the extra information passed by frontend on sign in, account. If we are going to use this functionality then I will refactor the documentation.

Option 2: If you don't want us to use this approach, frontend would have to send signature & account on sign in. Then I will refactor accordingly.

2021-04-25 16:18 UTC, venomnert commented on lib/cambiatus/auth/auth.ex
> +  end
Made the update

2021-04-26 00:57 UTC, lucca65 commented on lib/cambiatus/auth/auth.ex
> +    |> Session.get_auth()
keyword list?

2021-04-26 01:29 UTC, venomnert commented on lib/cambiatus/auth/auth.ex
> +    |> Session.get_auth()
That's correct, it's get passed directly into `where/3` which accepts keyword list.

2021-04-26 18:18 UTC, venomnert commented on lib/cambiatus/auth/auth.ex
> +    |> Session.get_auth()
Refactored to make it more clear

2021-04-27 16:38 UTC, closed without merging