Contribution documentation update
cambiatus/backend pull request #156
Opened 2021-04-27 20:22 UTC by venomnert

## Summary
Since we are an open source community our `readme` should strive to encompass developers of all experience. This can mean a beginning developer will want to make their first PR request; thus, we should explain the PR and release process.

## Changes Proposed ( a list of new changes introduced by this PR)
I have update our contribution to reflect accurately our PR and release process. 

## How to test ( a list of instructions on how to test this PR)
Review for any spelling and grammatical errors.

2021-04-28 21:47 UTC, lucca65 requested changes

2021-04-28 21:47 UTC, lucca65 commented on .github/contributing.md
> +    3. The issue is resolved.
I would change it a little bit, CI will check those stuff, not the reviewer (that point is under point 3) and the merge conflicts is also something that should be checked by the creator of the PR

2021-04-28 21:47 UTC, lucca65 commented on .github/contributing.md
> +1. After a PR has been merged into `master`. We will push the change to our [staging server](staging.cambiatus.io) to conduct our integration test.
actually its the contrary! we first deploy on staging and then make sure it works well, after getting the approval from the integration test is that we merge it! Of course some PRs don't actually change anything on the app, so its important to keep an eye out for the context of the issue, because, although we have similar processes, we need to be conscious for the context, more than the process. If the process blocks us from knowing the context, its only bureaucracy

2021-04-28 21:47 UTC, lucca65 commented on .github/contributing.md
> +3. If all test passes, then we are live!
we can actually deploy it to demo/production

2021-04-29 13:57 UTC, venomnert commented on .github/contributing.md
> +1. After a PR has been merged into `master`. We will push the change to our [staging server](staging.cambiatus.io) to conduct our integration test.
To reiterate your point on context @lucca65 . We need to ensure the context of the PR is clear throughout the process, because its the key information used by the reviewer to **comfortably** and **effectively** review the code.

2021-04-29 14:19 UTC, venomnert commented on .github/contributing.md
> +    3. The issue is resolved.
I have updated accordingly

2021-04-29 14:20 UTC, venomnert commented on .github/contributing.md
> +3. If all test passes, then we are live!
Included `demo` as well.

2021-04-29 21:22 UTC, lucca65 commented on .github/contributing.md
> +1. After a PR has been merged into `master`. We will push the change to our [staging server](staging.cambiatus.io) to conduct our integration test.
yeah, its important that the person that is working on the issue to know the context too, issue descriptions can help here, we will need to behave differently depending on the context. Context can be anything related to the task at hand, some examples of possible variables and informations that help us know how to act:

- a community badly needs it
- its a partial implementation
- its fixing something broke
- fixes for a live bug

and so on. You'll notice that know the context is a skill that the developer needs to have, not the process that need to define how she/he should do. Processes are useful, but we tend to try to find a perfect process and spend a lot of energy trying to come up with a reasonable and broad set of rules and steps, but that's not what we want to focus on Cambiatus.

Remember we are like sailors or hunters, we gather the data we need and act accordingly to the situation at hand, in a way that's the most vagabonding way possible: one that gives us a good mix of little stress, good reliability, top implementation and clear organization!

2021-04-29 21:28 UTC, lucca65 requested changes

2021-04-29 21:28 UTC, lucca65 commented on .github/contributing.md
> +If you find a security vulnerability, do NOT open an issue. Inform the #devs on the discord channel.
-1, we don't have a discord.... bad typo bro! please be more careful! Security vulnerability issues are welcomed to be talked about here, we even have some old ones addressed publicly on the past

2021-04-29 21:28 UTC, lucca65 commented on .github/contributing.md
> +3. Run the test suite `MIX_ENV=test mix test`. Please note we only accept pull requests with passing tests, and it's awesome to make one pass. Small contributions such as fixing spelling errors, wher
mix test already do the MIX_ENV thing

2021-04-29 21:28 UTC, lucca65 commented on .github/contributing.md
> +3. Run the test suite `MIX_ENV=test mix test`. Please note we only accept pull requests with passing tests, and it's awesome to make one pass. Small contributions such as fixing spelling errors, wher
also, forks should be avoided on inside collaborators, branchs are a much less confusing and equal in functionality if you are a collaborator

2021-04-29 21:28 UTC, lucca65 commented on .github/contributing.md
> +2. Prior to creating a PR ensure there are no merge conflicts.
actually, no problem to have draft PRs, or WIP PRs with merge conflicts, but to ask for a review, it needs to be able to be merged, otherwise the review would be automatically dismissed after the commit merge is pushed (although this is configurable on the repository settings)

2021-04-29 21:28 UTC, lucca65 commented on .github/contributing.md
> +5. At this stage the PR is ready for integration test. We will test the PR on our [staging server](staging.cambiatus.io). If the integration test passes then the PR is ready to be merged into `master
After getting the technical/code approval the next one is to get the approval from the test team

2021-04-29 21:35 UTC, venomnert commented on .github/contributing.md
> +If you find a security vulnerability, do NOT open an issue. Inform the #devs on the discord channel.
@lucca65 That sentence was already there. I just updated the format. However, I should have verified the existence of a discord channel with you. Here is the fixed sentence, "If you find a security vulnerability, we urge you to open an issue!"

2021-04-29 21:36 UTC, lucca65 commented on .github/contributing.md
> +If you find a security vulnerability, do NOT open an issue. Inform the #devs on the discord channel.
oh, right, sorry then! good that its spotted at least

2021-04-30 15:47 UTC, venomnert commented on .github/contributing.md
> +3. Run the test suite `MIX_ENV=test mix test`. Please note we only accept pull requests with passing tests, and it's awesome to make one pass. Small contributions such as fixing spelling errors, wher
* Removed `MIX_ENV=test`

> also, forks should be avoided on inside collaborators, branchs are a much less confusing and equal in functionality if you are a collaborator

This was the mistake I was making. After this PR I follow your guideline.

2021-04-30 16:07 UTC, lucca65 approved these changes
looking sweet 🍭

2021-04-30 16:17 UTC, merged