Add member_count to community preview
cambiatus/backend pull request #158
Opened 2021-04-29 21:34 UTC by lucca65

## What issue does this PR close
Closes N/A

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Add `memberCount` to `communityPreview` query
- [ ] Add photos for the community
- [ ] Add website to the community

## How to test ( a list of instructions on how to test this PR)
- `mix test`
- Check if communityPreview has a memberCount field and it is correct 
- Make sure its possible to add photos to the community, and only the creator can do it
- Make sure graphql allows you to have a website on a community and communityPreview

2021-05-02 14:17 UTC, venomnert requested changes

2021-05-02 14:17 UTC, venomnert commented on lib/cambiatus_web/controllers/upload_controller.ex
> +  alias Cambiatus.Upload.Uploader
Should be renamed to `Cambiatus.File.Uploader`

2021-05-02 14:17 UTC, venomnert commented on test/cambiatus/upload_test.exs
> +  alias Cambiatus.Upload.Uploader
Should be renamed to `Cambiatus.File.Uploader`

2021-05-03 13:10 UTC, venomnert commented
@lucca65 this PR also closes issue #155

2021-05-03 13:29 UTC, lucca65 commented
@venomnert since you are a organization member, you can edit the description of any PR, please feel free to update this one as well 💪

2021-05-03 19:12 UTC, venomnert requested changes

2021-05-03 20:33 UTC, lucca65 commented on lib/cambiatus/commune/community.ex
> +  end
hey bro, the behavior is intended!

2021-05-03 20:36 UTC, venomnert commented on lib/cambiatus/commune/community.ex
> +  end
Thanks for the confirmation!

2021-05-03 20:37 UTC, venomnert approved these changes

2021-05-04 13:15 UTC, merged