Feature/auth session
cambiatus/backend pull request #193
Opened 2021-11-08 20:59 UTC by adubas

pair with @flpfar 

## What issue does this PR close
Closes #141

## Changes Proposed ( a list of new changes introduced by this PR)
- Creates `auth_requests` migration
- Add `gen_auth` mutation that returns a phrase to be signed
- Add `gen_auth` resolver
- Creates a `create_request` function
- Creates a `get_request` function
- Refactor `verify_pass` function to verify if the password is the phrase signed
- Creates `get_public_key` and `verify_sign` functions. 
- Corrects tests

## How to test ( a list of instructions on how to test this PR)
On `http://localhost:4000/api/graphiql`, call the gen_auth mutation:
```
mutation{
  genAuth(account:"your_account") {
    phrase
  }
}
```
Get the `phrase`
Sign with your `private_key`
Then on `http://localhost:4000/api/graphiql`, call the sign_in mutation:
```
mutation{
  signIn(
    account:"your_account",
    password:"sign_phrase"
  )
  {
    token
  }
}
```
Get the `token`

2021-11-10 14:27 UTC, adubas commented
> @adubas @flpfar vamos marcar uma sessão juntos pra conversar mais sobre esse PR? Queria olhar esse com vocês! Posso marcar pra segunda no mesmo horário das nossas reuniões semanais?

Podemos marcar para terça? Segunda é feriado :sweat_smile:  e lembrando semana que vem o @flpfar estará de férias.

2021-11-10 14:31 UTC, lucca65 commented
Nossa, verdade né? esqueci do feriado mais uma vez, foi mal 🙇 

Vamos na terça as 15:30?

2021-11-10 14:37 UTC, adubas commented
> Nossa, verdade né? esqueci do feriado mais uma vez, foi mal bow
> 
> Vamos na terça as 15:30?

Perfeito!

2021-11-22 19:02 UTC, lucca65 commented
1. Create new session with `genAuth` 
2. Frontend pushes a transaction to the blockchain `validateAuth(phrase)` 
3. Contract validates user authority 
4. Event source updates session as validated
5. Frontend calls backend `signIn(account, phrase)`

2021-11-22 19:34 UTC, lucca65 requested changes
Somente a primeira tentativa signIn funciona. Se já foi criada uma sessão com essa frase, as próximas devem falhar, mesmo que o password seja valido, requests devem ser apagadas quando se transformarem em sessions

2021-11-29 17:10 UTC, lucca65 approved these changes
🔥 !!!

2021-12-01 19:27 UTC, lucca65 commented
@adubas can we merge this one?

2021-12-01 19:41 UTC, adubas commented
> @adubas can we merge this one?

Oh, yes we can, I was going to ask you if I could merge this.

2021-12-01 19:41 UTC, merged