Feature/shop refactor
cambiatus/backend pull request #220
Opened 2022-04-06 01:15 UTC by lucca65

## What issue does this PR close
Closes #

## Changes Proposed ( a list of new changes introduced by this PR)

- Remove blockchain data ingestion fields such as `created_tx` and `created_block` in favor of regular `inserted_at` and `updated_at`
- Add multiple photos to a single product
- Add several validations to product
- Allow products to be created and updated via GraphQL mutation

## How to test ( a list of instructions on how to test this PR)
- Run `mix test`

2022-04-07 22:44 UTC, lucca65 commented
@NeoVier com esse PR, vamos poder começar a usar o GraphQL para criar e editar anúncios. Vamos começar por esse passo primeiro, depois começamos a colocar dados novos, como categorias, disponibilidade de produtos, etc

2022-04-07 23:27 UTC, NeoVier requested changes
There's a bunch of comments just asking questions or reminding TODO comments.

I think we should at least address the `Product update failed` -> `Product creation failed` and `news is not enabled` -> `shop is not enabled` changes, as those could really trip us up in the future

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus/shop/product.ex
> +          else: add_error(changeset, :community_id, "news is not enabled")
Should this be "shop is not enabled"?
```suggestion
          else: add_error(changeset, :community_id, "shop is not enabled")
```

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus/shop/product.ex
> +  # @required_fields ~w(title description price track_stock units created_block is_deleted)a
I'm not sure I understand this comment. Should it still be here?

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus/shop/product.ex
> +  created_tx created_eos_account created_at inserted_at updated_at)a
Does it make sense to have both `created_eos_account` and `creator_id`? What are the differences? Same thing for `created_at` and `inserted_at`

Also, most of the optional fields seem like they should be required:
- `created_block`
- `creator_id`
- `created_tx`
- `created_eos_account`
- `created_at`
- `inserted_at`
- `updated_at`

Is there a scenario where we don't have these? I guess the blockchain-related ones could be optional (until the transaction to create the order is made), but I'm not sure about the others

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus_web/resolvers/shop.ex
> +        {:error, message: "Product update failed", details: Cambiatus.Error.from(reason)}
```suggestion
        Sentry.capture_message("Product creation failed", extra: %{error: reason})
        {:error, message: "Product creation failed", details: Cambiatus.Error.from(reason)}
```

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus_web/resolvers/shop.ex
> +      {:ok, product} = result ->
There's a warning here that `product` is unused
```suggestion
      {:ok, _product} = result ->
```

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +      # middleware(Middleware.Authenticate)
Should we do this now or should it remain commented out?

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
I wonder if we should have `track_stock` here... It creates the case where `track_stock` is true, but `units` is null. We can already know the value of `track_stock` just by checking if `units` is null or not.

2022-04-07 23:27 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:created_at, non_null(:datetime), deprecate: true)
Should we still keep these for now?

2022-04-07 23:27 UTC, NeoVier commented on priv/repo/migrations/20220405214735_multiple_shop_images.exs
> +      add(:uri, :string, null: false, comment: "URI for the image or video")
Ooh, having videos for products is interesting!!

2022-04-07 23:27 UTC, NeoVier commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> +      response =
There's a warning here that `response` is unused
```suggestion
      _response =
```

2022-04-07 23:41 UTC, lucca65 commented on lib/cambiatus/shop/product.ex
> +  # @required_fields ~w(title description price track_stock units created_block is_deleted)a
we will have to wait for it to be migrated on prod first. Since we do the migration of data from the blockchain timestamps to regular timestamps, they are actually optional.

after it's migrated we will have to come back here and change field requirements as also remove those columns as they will be obsolete

2022-04-07 23:46 UTC, lucca65 commented on lib/cambiatus/shop/product.ex
> +  created_tx created_eos_account created_at inserted_at updated_at)a
those blockchain related will be all removed after we are done with data migration on prod.

the other ones we don't have to worry about since ecto handle them. but we will need to change NULL rules so it's back to the regular default elixir model

2022-04-07 23:47 UTC, lucca65 commented on lib/cambiatus/shop/product.ex
> +          else: add_error(changeset, :community_id, "news is not enabled")
nice catch! thanks bro!

2022-04-07 23:47 UTC, lucca65 commented on lib/cambiatus_web/resolvers/shop.ex
> +        {:error, message: "Product update failed", details: Cambiatus.Error.from(reason)}
there is two upsert function matches, this one only handle update

2022-04-07 23:50 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
this validation is made on product model, since it can be empty only depending on the value of track_stock

2022-04-07 23:51 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:created_at, non_null(:datetime), deprecate: true)
yes, we will need to migrate data before removing those fields

2022-04-07 23:51 UTC, lucca65 commented on priv/repo/migrations/20220405214735_multiple_shop_images.exs
> +      add(:uri, :string, null: false, comment: "URI for the image or video")
and for us super simple! just a uri! 🤠

2022-04-07 23:56 UTC, NeoVier commented on lib/cambiatus_web/resolvers/shop.ex
> +        {:error, message: "Product update failed", details: Cambiatus.Error.from(reason)}
Isn't this the create one? It calls `Shop.create_product()`. Either way, both of the function matches have `Product update failed`:
![image](https://user-images.githubusercontent.com/39280468/162337697-2689004e-7e84-48a5-8f7b-f5021f1f1ef2.png)

2022-04-08 00:00 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
Yeah, but we won't know that on the frontend when we fetch it... We'll only see that `trackStock` is a `Bool` and `units` is a `Maybe Int`.

We can catch this on the `selectionSet`, so it won't ever bleed out onto the actual app logic, so it's not a big problem anyway

2022-04-08 15:14 UTC, lucca65 commented on lib/cambiatus_web/resolvers/shop.ex
> +        {:error, message: "Product update failed", details: Cambiatus.Error.from(reason)}
oh damn, sorry bro, you are right! thanks!

2022-04-08 15:17 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
but it makes sense in a data design point of view right? Track stock is mandatory, but units will only be on a few scenarios.

2022-04-08 15:18 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +      # middleware(Middleware.Authenticate)
should be removed, thanks bro!

2022-04-08 15:21 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
It does, but ideally we'd have a custom type like

```elm
type StockTracking
    = NoTracking
    | TrackUnits { units : Int }
```

I'm not really sure if it's doable with elixir/SQL/GraphQL though. I think Elm has spoiled me 😅

2022-04-08 15:24 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
well, we could use [union types](https://graphql.org/learn/schema/#union-types), I'll fiddle around to implement it. We have no way to do this on postgres/ecto, as far as I know, but we can on graphql

2022-04-08 15:25 UTC, NeoVier approved these changes
Looks good now! Just needs a fix on a test

2022-04-08 15:25 UTC, NeoVier commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> +                   "details" => %{"community_id" => ["news is not enabled"]},
Tests are breaking due to the change on this string
```suggestion
                   "details" => %{"community_id" => ["shop is not enabled"]},
```

2022-04-08 19:32 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
Bro, this is actually good but doesn't seem like I can do this type of query with no fields inside:

```graphql
mutation {
  product(id: 1) {
    ... on NoTracking {}
    ... on TrackingUnits { units } 
  } 
}
```

Makes some-ish sense, union types were thought when we had a type that describes them and redirect to different entities, like we do on the `notification.payload`... Guess we will have to keep it like that, at least for now

For the future we will have different types of products, like `digital`, `downloadable`, `nft`, `trackable` (in a has delivery sense), `stockable`. That will be used to allow different behaviors. Maybe we can add units as a type. We can think in more depth about this in the future!

2022-04-08 19:38 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +    field(:units, :integer)
Ok, awesome!

2022-04-26 01:19 UTC, NeoVier commented on lib/cambiatus_web/schema/shop_types.ex
> +    end
Should this have an optional `id` field? Otherwise, how do we update existing products?

Also, is `community_id` needed here? Can't we get the community through the absinthe context?

2022-04-26 01:38 UTC, NeoVier commented
Besides creating and updating, we also have `deletesale` on the smart contracts, which is missing in this PR. Are we treating the deletion through GraphQL as well?

2022-04-27 02:40 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    end
it does! I'll ping you in the test so you can have an example

2022-04-27 02:41 UTC, lucca65 commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> +          product(id: #{product.id},
@NeoVier check this test out, it contains an update mutation for reference, just send the ID

2022-04-27 02:46 UTC, lucca65 commented on lib/cambiatus_web/schema/shop_types.ex
> +    end
About the community ID, its not on the absinthe context, although it could be. See, we use the `Community-Domain` header only on sign up as this is required for us to know how to handle invitations and netlinks (both happen on signIn and signUp).

We could add this as an automatic context for sure. To handle that I've opened this issue: https://github.com/cambiatus/backend/issues/223

2022-04-27 12:06 UTC, NeoVier commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> +          product(id: #{product.id},
That's weird bro, it doesn't show up in the schema (elm-graphql needs it to be on the schema so it can generate code), and it won't allow me to give it an id even if I try:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/39280468/165514050-19c4aec4-ec95-4f33-9bde-50f71f174940.png">

Also, all of the fields are required... How is that test passing? 🤔

2022-04-27 14:04 UTC, lucca65 commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> +          product(id: #{product.id},
wow, this is weird... I'll check it out bro! oh, I'll implement a delete mutation as well

2022-04-27 23:46 UTC, lucca65 commented
@NeoVier turns out I've done the update tests with `=` instead of `==` 🤦 

I've done improvements and implemented the `deleteProduct` mutation, let me know if it works properly for you!

2022-04-27 23:59 UTC, NeoVier commented
Welp, that must've been a fun one to debug 🤣

I'll test them out and let you know!

2022-04-28 00:49 UTC, NeoVier requested changes

2022-04-28 00:49 UTC, NeoVier commented on lib/cambiatus/shop/product.ex
> +         (not is_nil(units) and units > 0) do
I think there's a logic error here... If I give it `track_stock = false` and don't provide `units`, it still says `cannot be filled if track_stock is false`.

Maybe we want `not is_nil(units) or units > 0`? Maybe even just `not is_nil(units)` is enough?

Here's the mutation I'm running:
```graphql
mutation {
  product(id: 57, trackStock: false) {
    trackStock
    units
  }
}
```

2022-04-28 01:38 UTC, NeoVier commented
Also, I can't add images to a product. When I try, I just get a 500 Something went wrong

Here's the mutation I'm trying:

```graphql
mutation {
  product(id: 57, images: ["https://cambiatus-uploads.s3.amazonaws.com/cambiatus-uploads/7c283b3afe8d47ffa7345c6dbbd865d2"]) {
    images
  }
}
```

2022-04-28 20:19 UTC, lucca65 commented on lib/cambiatus/shop/product.ex
> +         (not is_nil(units) and units > 0) do
ok, I've looked into this and what happens is that you are setting track_stock as false on a product that have units already. Do it like this and it will work:

```elixir
mutation {
  product(id: 57, trackStock: false, units: 0) {
    trackStock
    units
  }
}
```

2022-04-29 01:13 UTC, NeoVier commented on lib/cambiatus/shop/product.ex
> +         (not is_nil(units) and units > 0) do
Ok, that makes sense 🤦

2022-04-29 01:46 UTC, NeoVier commented
Uploading images works, but querying for the `images` field on old products gives a `Cannot return null for non-nullable field`. I see there's a migration to migrate that data, but when I try to run migrations, I just get `Migrations already up`:

![image](https://user-images.githubusercontent.com/39280468/165873237-3df01da7-2292-4efc-a8d9-eb4d76455195.png)

Here's the mutation I'm trying, and the error I'm getting:

```graphql
query {
  products(communityId: "0,BUSS") {
    images {
      uri
    }
  }
}
```

<img width="588" alt="image" src="https://user-images.githubusercontent.com/39280468/165873289-abeff190-7663-4ddb-af22-1c19aa3e0eea.png">

2022-04-29 16:21 UTC, lucca65 commented
Hours of debugging, database dumping for a single line fix ✊😮‍💨

2022-04-29 16:51 UTC, NeoVier approved these changes
It's working now! If you want, you can do your own testing on the frontend PR here: https://github.com/cambiatus/frontend/pull/734

The only thing that I'm not sure is intended is that the old `image` is not included in the new `images` list. It's ok for now from the frontend point of view, but might be a little more annoying once we start working on supporting multiple images

2022-04-29 16:57 UTC, NeoVier commented
Oh, I just realized: is this PR problematic for `ProductPreview`s? Are we supporting multiple images on those as well? Are they consuming the new `images` that we now upload?

2022-04-29 17:31 UTC, lucca65 commented
> The only thing that I'm not sure is intended is that the old image is not included in the new images list. It's ok for now from the frontend point of view, but might be a little more annoying once we start working on supporting multiple images

Bro no need to worry too much about this, we will have to do a migration in such a way that we will not need to handle this. You can always simply show `Images` and drop checks or usage on `image`

2022-04-29 20:05 UTC, NeoVier approved these changes
Images are working 📷 👍

2022-05-05 00:25 UTC, merged