Created manifest controller and implemented get_subdomain function
cambiatus/backend pull request #222
Opened 2022-04-19 01:14 UTC by MatheusBuss

## What issue does this PR close
Closes #218 

## Changes Proposed ( a list of new changes introduced by this PR)
Implement community subdomain as a required header to `conn`

## How to test ( a list of instructions on how to test this PR)
Run `mix test`
Submit a `get` request to `\manifest`

2022-04-21 22:48 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      |> Map.get(:domain)
+1, on map navigation you can use the `.` operator. You can debug and test this out before doing the function calls by calling `iex -S mix phx.server`. After this you can add on your code a breakpoint that will stop execution on the line you choose. 

This [article is kinda bad](https://medium.com/scientific-breakthrough-of-the-afternoon/inspecting-changesets-with-iex-pry-in-phoenix-app-forms-d03ebf96cb8f) but it does show the point in a good enough context


From there you can simply type `conn` on the stopped console breakpoint and explore the values at will

2022-04-21 22:51 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        {:error, "No subdomain provided"}
+1 we will have to get the origin header that will always work, with the ability to fallback to a default image. The way its done here, we rely on a GraphQL specific query, which we won't get automatically formatted in a way that defaults to a simple image, as it will always return a JSON.

so, TLDR; we should get `Host` from header, instead of `Community-Domain`, this is a standard header, sent by all browsers that we are able to read. This URL should be matched inside elixir with the community domain

2022-04-21 22:55 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        |> Commune.get_community_by_subdomain()
maybe this can be a little different:

```elixir
with {:ok, %{host: host}} <- get_subdomain(conn),
  {:ok, community} <- Commune.get_community_by_subdomain() do
. . . 

else 
  # Community not found 
  {:error, _} → 
      # Show default manifest file, that can be hardcoded
  
  _ → 
    # Same error as before
end
```

2022-04-21 22:56 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        |> Commune.get_community_by_subdomain()
This way we handle the case where an community without a domain still works

2022-04-25 19:29 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        {:error, "No subdomain provided"}
I have set it up so that the domain references `conn` directly, but I'm not entirely sure if that's what you meant by getting from the header. So I also left `subdomain = conn.private.absinthe.context.domain` as a fallback, even though I'm pretty sure it's never going to trigger.  I had talked with @NeoVier about using the `domain` from `conn` and he said there were some problems with this approach, since there are situations where the correct host is not provided.

2022-04-25 19:33 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      |> Map.get(:domain)
I have made this change, though it resulted in some problems when I tried as localhost. Since I have not provided a domain, using the `.` operator returned an error, since it could not find  `:domain` inside the map, whereas the method `Map.get` returns `nil`. I would't think this is a problem, since during an actual connection the `:domain` value should always exist.

And thanks for the debugging tips, I have already spent some time with them 😉.

2022-04-25 19:34 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        |> Commune.get_community_by_subdomain()
Ok, I have made some changes as to create a placeholder community and serve its json.

2022-04-27 02:51 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      |> Map.get(:domain)
you could pattern match to make sure it have the necessary format:

```elixir
with %{a: %{b: x, c: %{d: value}}} <- conn do 
end
```

2022-04-27 18:12 UTC, lucca65 requested changes

2022-04-27 18:12 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      {:ok, subdomain}
```elixir
case conn.host do
  community_url when is_binary(community_url) → 
    {:ok, community_url}
  
  _ → 
    {:error, "No community url provided"}
end
```

2022-04-27 18:12 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      serve_manifest_json(conn, community)
Talvez, ao invés de servir um manifest padrão, a gente pode dar um 301 (https://httpstatuses.zander.wtf) 

@MatheusBuss dá uma testada junto com o @NeoVier se dá pra mostrar no navegador adequadamente

2022-04-27 18:16 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +  end
For reference we already have a controller test: https://github.com/cambiatus/backend/blob/master/test/cambiatus_web/controllers/invite_controller_test.exs

2022-04-27 18:45 UTC, NeoVier commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      serve_manifest_json(conn, community)
Qual seria a motivação de não servir o manifest padrão? Ao meu ver, não tem desvantagem servimos o padrão.

O `Commune.get_community_by_subdomain` vai falhar quando:
1. O usuário entrar numa url que não corresponde a uma comunidade (ex: `exemplo.cambiatus.io`)
2. Estamos rodando o frontend com USE_SUBDOMAIN=false, ou seja, as comunidades vivem todas no mesmo domínio.

No caso 1, o usuário é redirecionado ao seletor de comunidades. Talvez o usuário pertença a várias comunidades, e o seletor de comunidades seja uma página útil para ele. Nesse caso, salvar o app só como `Cambiatus` e abrir nessa página seria uma coisa boa.

No caso 2, nunca conseguiremos instalar o app se retornarmos um erro ao invés de um manifest padrão.

2022-04-27 18:49 UTC, NeoVier requested changes

2022-04-27 18:49 UTC, NeoVier commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      start_url: community.website,
This should be `community.subdomain`:
```suggestion
      start_url: community.subdomain,
```

https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url

2022-04-27 19:04 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      serve_manifest_json(conn, community)
ah, estava falando com o @MatheusBuss por zoom, acho que mandei mal na explicação, a ideia é dar um 301 pra https://app.cambiatus.io/manifest.json

2022-04-27 19:05 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      serve_manifest_json(conn, community)
assim o redirect vai pro manifest.json do front, acho que dessa maneira, se o navegador conseguir seguir esse 301 apropriadamente, resolve.

agora se o navegador ou celular com seus instaladores de pwa não conseguir seguir o 301, aí seguimos com a entrega do json por aqui mesmo

2022-04-28 03:17 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      serve_manifest_json(conn, community)
Fiz para retornar o 301. Podemos ver se vai funcionar como esperado @NeoVier, se necessário voltamos para manifest padrão mesmo.

2022-04-28 03:22 UTC, MatheusBuss commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +      {:ok, response} = Poison.decode(response, keys: :atoms)
I'm not entirely sure why this happened, but the json I received on the test was encoded twice, or at least I had to decode it twice, Surely there is a better way to implement this, right @lucca65?

2022-04-28 11:36 UTC, NeoVier requested changes

2022-04-28 11:36 UTC, NeoVier commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        |> put_status(301)
You still need to add the `Location` header here, according to MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

Otherwise, the browser wouldn't know where it's being redirected to. You can set it to `/manifest.json`

2022-04-28 11:37 UTC, NeoVier commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        |> put_status(301)
After this change, we can talk to test it out! 🏃‍♂️

2022-04-28 14:30 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +        |> put_status(301)
The redirect should be working now! With the 301 status and the `Location` header

2022-04-28 14:31 UTC, MatheusBuss commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +      {:ok, response} = Poison.decode(response, keys: :atoms)
I figured it out, already fixed

2022-04-28 14:36 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/manifest_controller.ex
>          |> manifest_template()
I was getting an error because `Ecto` was not loading the community struct correctly. I've implemented the suggestion I got from running the tests, not sure if this won't cause problems further ahead @lucca65.

2022-04-28 20:22 UTC, lucca65 commented on lib/cambiatus_web/controllers/manifest_controller.ex
>          |> manifest_template()
no, that's pretty standard, you are loading related data needed to our manifest file!

2022-04-29 01:03 UTC, NeoVier commented on lib/cambiatus_web/controllers/manifest_controller.ex
> +      serve_manifest_json(conn, community)
Só pra registrar, eu e o @MatheusBuss testamos hoje, e está funcionando! Tanto o manifest para comunidades que existem, tanto o redirect pro manifest do frontend 🎉

2022-04-29 01:05 UTC, NeoVier approved these changes
From the frontend perspective, this is working very well 💪 (maybe we should also wait for an approval from @lucca65 though)

Congrats on the first PR @MatheusBuss!

2022-04-29 15:01 UTC, lucca65 requested changes

2022-04-29 15:01 UTC, lucca65 commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +  end
Since this test only applies to the manifest controller, we should put the community header on the setup, I think

2022-04-29 15:01 UTC, lucca65 commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +         %{conn: conn} do
and in this case we simply build a new conn: 

```elixir
build_conn()
```

2022-05-02 20:04 UTC, MatheusBuss commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +         %{conn: conn} do
Using `build_conn()` now!

2022-05-02 20:06 UTC, MatheusBuss commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +  end
I've made it so it gets the community from the already defined `valid_community_and_user` from the `DataCase`, I think this should be enough, right @lucca65?

2022-05-02 20:32 UTC, lucca65 commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +  end
yeah, it should be enough!

2022-05-02 20:34 UTC, lucca65 approved these changes
just a stylistic change, it looks good to me otherwise!

2022-05-02 20:34 UTC, lucca65 commented on test/cambiatus_web/controllers/manifest_controller_test.exs
> +        |> Repo.preload(:subdomain)
No need to use pipe on only one function:


```suggestion
        Repo.preload(community, :subdomain)
```

2022-05-02 21:29 UTC, lucca65 approved these changes

2022-05-02 21:34 UTC, merged