Created rich_link_controller and functionalities
cambiatus/backend pull request #227
Opened 2022-05-08 18:36 UTC by MatheusBuss

## What issue does this PR close
Closes #182

## Changes Proposed (a list of new changes introduced by this PR)
Add rich link/preview when Cambiatus andand associated links are shared in different social medias

## How to test ( a list of instructions on how to test this PR)
1. Run `mix phx.server`
2. Send HTTP request for differente funcionalities
  2.1. For User sharing send `GET` request to `/api/rich_link/profile/#{user_name}`
  2.2. For Product sharing send `GET` request to `/api/rich_link/shop?id=#{product_id}`
  2.3. For Community sharing send `GET` request to `/api/rich_link` (Use the host header in the HTTP request for the appropriate community)
3. Check html info sent by the server

2022-05-10 14:09 UTC, MatheusBuss commented
The Elixir part should be working now. Sharing the HTML generated by the phoenix server worked on WhatsApp, Slack and Facebook. Twitter was not yet tested.

Some of the next steps that I have discussed with @NeoVier:
1 - Use NGINX to redirect the `GET` request from social media web crawlers based on their user agents (we can look into this list https://developers.whatismybrowser.com/useragents/explore/software_name/)
2 - Check if all the fields are beign filled correctly according to the Open Graph Protocol (https://ogp.me/)

2022-05-10 14:28 UTC, NeoVier commented on lib/cambiatus_web/router.ex
> +    get("/rich_link/*page", RichLinkController, :rich_link)
At the end of the day, we could use any url we want, since we will rewrite urls with nginx, right?

2022-05-10 14:29 UTC, lucca65 commented on lib/cambiatus_web/router.ex
> +    get("/rich_link/*page", RichLinkController, :rich_link)
right, the prefix don't really matter, but I'm suggesting that we drop `/profile` and `/shop` and infer it based on the data type

2022-05-10 21:14 UTC, MatheusBuss commented on lib/cambiatus_web/router.ex
> +    get("/rich_link/*page", RichLinkController, :rich_link)
We can certainly do it this way too. I was just thinking that it would be easier to implement the current iteration on NGINX, since ot only requires to add `/api/rich_link/` to the requested path.

But we could look into doing the logic of tranforming the URL into the way you mentioned.

2022-05-10 21:21 UTC, MatheusBuss commented
> bro, when the bio has markdown we don't render it properly, like you can see on https://api.staging.cambiatus.io/api/rich_link/profile/lucca (I've published it to staging).

Using [`pandex`](https://github.com/FilterKaapi/pandex) I was able to convert markdown to plain text, so it shouldn't be a problem then. But this alternative requires the installation of `pandex` itself and [Pandoc](https://pandoc.org/).

I've tried approaching it using [`Earmark`](https://hexdocs.pm/earmark/Earmark.html) (which is already on `mix.exs`), but it only converts into HTML os AST as far as I can tell. Therefore we eould need to convert this HTML into plain text too.

So I believe we should try to use `pandex` going forward

2022-05-10 23:33 UTC, lucca65 commented on lib/cambiatus_web/router.ex
> +    get("/rich_link/*page", RichLinkController, :rich_link)
I guess you could do the data type checking on nginx as well, no problem for me. Maybe we can have the NGINX configurations in our README setup section, so this don't get lost if we switch servers in the future.

2022-05-10 23:34 UTC, lucca65 commented
Ok @MatheusBuss! Np for pandoc

2022-05-11 11:40 UTC, lucca65 requested changes
Also tests? 😬 🔧

2022-05-11 11:40 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +          |> Enum.into([])
Since we only allow markdown on description (both for profile and product) shouldn't we only try to parse for those fields? The way it is we are putting every field to possible parsing. It will be resource heavy to do this for every field on every request when we don't need to

2022-05-11 11:50 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +          |> Enum.into([])
Sure thing, I'll be doing that then

2022-05-12 12:48 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +          |> Enum.into([])
Done!

2022-05-12 12:53 UTC, MatheusBuss commented
Still to do:
- Use Phoenix's views to render the template
- Implement NGINX redirect
- Rewrite some template fields to properly comply to the Open Graph Protocol

2022-05-13 14:19 UTC, lucca65 requested changes
Its getting better and better bro! Keep it up!

2022-05-13 14:55 UTC, lucca65 requested changes

2022-05-13 14:55 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
>    """
please move `@moduledoc` to the first statement on the module, instead of the `use` macro

2022-05-13 17:34 UTC, lucca65 commented
a URL precisa ser pra tela do perfil, ao invés do email

2022-05-20 17:19 UTC, lucca65 requested changes
Sorry for the long time to work on the review @MatheusBuss

2022-05-20 17:19 UTC, lucca65 commented on README.md
> +Now you can make HTTP requests to NGINX on your browser under localhost!
Maybe we can simply link to nginx documentation, the part that we need is only the relevant configuration changes

2022-05-20 17:19 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +        [image | _] = product.images
This may fail, images can be an empty array. Maybe this is a good way to explore https://www.openmymind.net/Elixirs-With-Statement/

2022-05-20 17:19 UTC, lucca65 commented on lib/cambiatus_web/views/rich_link_view.ex
> +      |> String.trim()
if there is a pipe, use it all the way:

```suggestion
      string
      |> HtmlSanitizeEx.strip_tags()
      |> String.trim()
```

2022-05-20 17:19 UTC, lucca65 commented on nginx/nginx.conf
> +}
This file is huge, no way we need 207 lines to describe this. You can add only the relevant part and it can be directly under our README.md file

2022-05-20 17:19 UTC, lucca65 commented on test/cambiatus_web/controllers/rich_link_controller_test.exs
> +      assert conn.status == 200
+1

2022-05-24 14:58 UTC, lucca65 requested changes
I liked the instructions. Just followed it now and tested on telegram.

here is the result for this URL: https://api.staging.cambiatus.io/api/rich_link/profile/lucca
<img width="483" alt="Captura de Tela 2022-05-24 às 11 54 28" src="https://user-images.githubusercontent.com/1082127/170066353-728dff87-5960-4ea8-bcc0-fdff51557f6e.png">

I'm missing the photo and we also have a <u> tag that was not rendered correctly. 

Also its rendering some sort of lorem ipsum, even if my profile don't have it:

<img width="625" alt="Captura de Tela 2022-05-24 às 11 57 46" src="https://user-images.githubusercontent.com/1082127/170067147-20a60b3d-29be-448b-9d50-904b0707bb2c.png">

2022-05-24 18:48 UTC, MatheusBuss commented
> Also its rendering some sort of lorem ipsum, even if my profile don't have it

That's odd. I tested on Telegram and had the same result, but on WhatsApp it renders correctly (other than the underline tag and the image)
![image](https://user-images.githubusercontent.com/102705968/170105922-f2bcad7c-dd1e-4546-a774-39b1327e43df.png)

Even checking the html on the page it doesn't have any lorem ipsum in it. Don't know why it shows on Telegram, maybe it's cached from previous tests?

> I liked the instructions. Just followed it now and tested on telegram.

We should try to use an URL withouth the `/api/rich_link` to test if nginx is redirecting correctly the crawlers (something like [https://buss.staging.cambiatus.io/profile/mattheusbuss](https://buss.staging.cambiatus.io/profile/mattheusbuss)). I even tried with this link, but it didn't work.

2022-05-24 19:11 UTC, MatheusBuss commented
> Don't know why it shows on Telegram, maybe it's cached from previous tests?

Exactly this. I found [@webpagebot](https://telegram.me/webpagebot) on [this thread](https://stackoverflow.com/questions/34707915/how-do-you-clear-the-open-graph-cache-of-an-url-on-telegram) . It clears the cache on telegram. Now the description is updated!

![image](https://user-images.githubusercontent.com/102705968/170113569-6dcbd982-07b6-4dbb-a2ff-95e86ed7a86a.png)

2022-05-25 21:46 UTC, lucca65 commented
Great bro this is awesome! Can we also preview the profile image when sharing profile links?

2022-05-25 21:56 UTC, MatheusBuss commented
I was looking into it, and the html does include the image link, but it isn't loading. I tried downloading based on the link and noticed that the file doesn't have the extension (.jpeg or .png) so it could be that.
Another reason might be the image size. Facebook limits the image size to 8MB ([per the developer page](https://developers.facebook.com/docs/sharing/webmasters/images/)) but I remember reading some recommendations to limi the size to 30 kB, but I will have to double check on that.

2022-05-26 17:46 UTC, MatheusBuss commented
> I see bro, in this case can you open a new issue for us to transform images on this link? This way we can tackle this in a part two

Created #239

2022-05-30 22:58 UTC, lucca65 approved these changes
Looks good to me! congrats bro!

2022-05-31 05:26 UTC, NeoVier requested changes

2022-05-31 05:26 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +          "https://buss.staging.cambiatus.io/images/logo-cambiatus-mobile.svg"
I don't think it's a good idea to point to a staging community to get this logo. If someday we decide to change the name of that file in staging, it could affect production. Maybe @lucca65 can give better directions on where to store this (on the server itself, on AWS, or somewhere else), but here's the image for you to use:

![logo-cambiatus-mobile](https://user-images.githubusercontent.com/39280468/171096977-8d602988-aea1-4552-a032-945af0ff97fc.svg)

2022-05-31 05:26 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           url: community_subdomain,
From https://ogp.me:

> og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "https://www.imdb.com/title/tt0117500/".

I think we should use the product's url here, which would look something like `https://buss.staging.cambiatus.io/shop/#{product.id}`

2022-05-31 05:26 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           url: community_subdomain,
Same thing as the product url. The profile url looks like `https://buss.staging.cambiatus.io/profile/#{user.account}`

2022-05-31 05:26 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           title: user.name,
I'm not sure if this is true in the backend as well, but in the frontend, `user.name` can be null. Maybe we should check this here, and display `user.account` if `user.name` is null

2022-05-31 05:26 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +            community_rich_link(community_subdomain)
Nice 🎉

2022-05-31 05:26 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           image: get_image.(product),
Elixir syntax is so weird 💀

2022-05-31 12:17 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +          "https://buss.staging.cambiatus.io/images/logo-cambiatus-mobile.svg"
We may have to look more into this, since it seems that [svg's are not accepted on OG's](https://developers.facebook.com/docs/sharing/webmasters/#images](https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images)). We should look instead into [using, jpeg, png or even gif](https://developers.facebook.com/docs/sharing/webmasters/#images).

Maybe this is something that can be addressed on #239.

2022-05-31 12:19 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +            community_rich_link(community_subdomain)
Thanks for the reviews! 😁

2022-05-31 15:08 UTC, merged