Improvement on kyc error message when document is no valid
cambiatus/backend pull request #240
Opened 2022-05-27 02:13 UTC by MatheusBuss

## What issue does this PR close
Closes #211 

## Changes Proposed ( a list of new changes introduced by this PR)

- [ ] Validate and point out different errors when entering document information
    - [ ] Check number of digits
    - [ ] Check dashes placement
    - [ ] Check if leading number is not zero
    - [ ] Check if only digits were used

- [ ] Update tests to check for new validations
    - [ ] Test for number of digits
    - [ ] Test for dashes placement
    - [ ] Test if leading number is not zero
    - [ ] Test if only digits were used

2022-05-27 13:56 UTC, MatheusBuss commented
> but this seems like the perfect instance to start looking at [TDD](https://www.agilealliance.org/glossary/tdd/).

Yeah, I agree, but I haven't quite gotten my mind around to TDD yet. At this point the code is almost complete (but probably could use some refactoring) so I'll have to start on TDD on another date :( . Thanks for the heads up though.

2022-05-27 18:52 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +    case Enum.count(graphemes, fn x -> x == "-" end) != Enum.count(positions) do
```elixir
(fn x → x == "-" end) == &(&1 == "-")
```

2022-05-27 18:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +          string_length: [12]
```elixir
fn len, val → String.length(val) == len end
&(String.length(&2) == &1)

fn min, max, val → String.length(val) >= min || String.length(val) <= max end
```

2022-06-01 16:55 UTC, lucca65 requested changes
bro olhando esse monte de código, fiquei aqui pensando, pq não fazemos a higiene da string (tirar os eventuais `-`.)e só validamos com a regex normal?

Para a validação de `check _null_first_digit`, nós precisamos fazer isso? A regex consegue olhar isso também.

2022-06-01 16:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
>      # changeset =
lost comment here

2022-06-01 16:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +         true <- input_length < min_length || input_length > max_length do
Achei um pouco confuso esse `with` bro. Geralmente o with é o "happy path", onde tudo deu certo. Você tem 3 linhas pra criar variável e depois só uma única condição. 

Daria pra jogar esses valores pra fora do `with` e verificar com um flow mais simples.

2022-06-01 16:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +  # defp check_null_first_digit(changeset, )
comentário perdido

2022-06-01 16:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +    # changeset =
Comentário perdido

2022-06-01 16:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +      graphemes =
Além dos comentários perdidos, seu `with` tá com clausulas que sempre vão bater, fazendo o `else` ser inalcançável

2022-06-01 16:55 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +    # changeset =
mais um comentário perdido. Se te ajudar você pode colocar um 
```suggestion
    # TODO: remover
    # changeset = 
```

Esse `TODO:` é uma sintaxe especial que é compatível com várias ferramentas de desenvolvimento, inclusive com as padrão que vem no Visual Studio, que te ajudam a lembrar de pedaços de código como esse que ficaram pra trás na revisão

2022-06-01 21:47 UTC, MatheusBuss commented
> bro olhando esse monte de código, fiquei aqui pensando, pq não fazemos a higiene da string (tirar os eventuais `-`.)e só validamos com a regex normal?

+1, já simplifica bastante coisa. Inlcusive, pelo que testei, o frontend só aceita números nos campos de documentos, @NeoVier pode me corrigir se estiver errado. Daí só higieniza as entradas e adapta as regexes para trabalharem com dígitos.

> Para a validação de `check_null_first_digit`, nós precisamos fazer isso? A regex consegue olhar isso também.

Essa flag seria só pra diferenciar os documentos que requerem um dígito não nulo e os documentos que não requerem, pra ele acusar de maneira certa. A regex pega sim, mas em alguns documentos não tem problema esse primeiro dígito ser nulo.

2022-06-01 21:53 UTC, NeoVier commented
> o frontend só aceita números nos campos de documentos

Parece que sim. De qualquer maneira, os `-` são dados de apresentação. Talvez seja melhor guardar no backend sem eles, e se quisermos mostrá-los, adicionamos no frontend

2022-06-01 22:43 UTC, MatheusBuss commented on lib/cambiatus/kyc/kyc_data.ex
> +    # changeset =
Valeu pela dica! Esses comentários passaram batidos por mim, foi mal pelo trabalho a mais.

2022-06-01 22:45 UTC, MatheusBuss commented on lib/cambiatus/kyc/kyc_data.ex
> +    end
Fiquei um pouco na pira de tentar evitar o `if` por ser "menos idiomático", mas vou tentar usar ele mais então.

2022-06-01 22:59 UTC, MatheusBuss commented
> Parece que sim. De qualquer maneira, os `-` são dados de apresentação. Talvez seja melhor guardar no backend sem eles, e se quisermos mostrá-los, adicionamos no frontend

Higienizei os dados só pra fazer a verificação. Imagino que pra higienizar todos os dados que vão entrar seria bom também higienizar os dados que já estão guardados. Se for o caso podemos abrir uma issue pra isso @lucca65?

2022-06-02 11:43 UTC, lucca65 commented
Acho que não precisa bro, esses dados foram feitos só para ter um acompanhamento que era necessário na época

1. Tirar os `-` só para validar
2. Guardar como vier

2022-06-02 11:52 UTC, lucca65 approved these changes
This looks good bro! I've gave a suggestion but its optional, just to explore different ways to control flow in elixir. You've implemented `case`, `with` and `if`, there is an extra one, that is function pattern matching.

2022-06-02 11:52 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +  end
bro, just for the fun of it, and to give you more tools for working, can you convert this to a pattern matched function?
```elixir
def get_document_type_pattern("mipyme") do
  %{}
end

def get_document_type_pattern("gran_empresa") do
  %{}
end
```

2022-06-02 12:07 UTC, MatheusBuss commented on lib/cambiatus/kyc/kyc_data.ex
> +  end
Man, there are **so many** tools to use! So many ways to make the code look better.

2022-06-02 12:11 UTC, lucca65 approved these changes

2022-06-02 12:13 UTC, merged

2022-06-02 12:17 UTC, lucca65 commented on lib/cambiatus/kyc/kyc_data.ex
> +  end
well the artist needs a lot of brush types 🧑‍🎨 🎨