Feature/categories filter for shop products
cambiatus/backend pull request #246
Opened 2022-06-08 20:01 UTC by MatheusBuss

## What issue does this PR close
Closes #242 

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Create filter for products based on categories
- [ ] Create test for filter

## How to test ( a list of instructions on how to test this PR)
Run `mix test test/cambiatus_web/schema/resolvers/shop_test.exs`

2022-06-08 20:03 UTC, MatheusBuss commented
This implementation is failing because the join results in duplicate entries when a product is in two categories being queried at the same time. This is still to be fixed.

2022-06-08 20:16 UTC, NeoVier commented
@MatheusBuss since this depends on #237 , it might be a good idea to change the target branch to be `feature/shop-categories`. If you don't, and you finish this before #237, you will end up pushing all of the code of that PR to `master` before it's done. It will also make this PR a lot easier to review, since it will only show the differences between this PR and #237 

(At least I think so, maybe @lucca65 can correct me if I'm wrong 😅)

To do it, click "Edit" on the top of the page, and change the dropdown that says "base:master" to the correct branch

![Untitled](https://user-images.githubusercontent.com/39280468/172708446-37273fbb-16d2-4d53-8dfd-8506b3787a1c.png)

2022-06-08 20:20 UTC, lucca65 commented
@NeoVier acho que podemos mirar a master aqui, mas com a disciplina de não mergear/aprovar até o outro PR, acho que assim fica melhor do que ter um PR grandão.

2022-06-08 20:47 UTC, lucca65 requested changes

2022-06-08 20:47 UTC, lucca65 commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> -        |> json_response(200)
why remove this line?

2022-06-08 21:16 UTC, MatheusBuss commented on test/cambiatus_web/schema/resolvers/shop_test.exs
> -        |> json_response(200)
Happened by accident when pulling the origin into the branch. Had a conflict with another PR.

2022-06-13 14:33 UTC, lucca65 approved these changes
✅ Awesome! I'll merge it right away!

2022-06-13 14:33 UTC, merged