Added price and creator to description
cambiatus/backend pull request #248
Opened 2022-06-13 16:47 UTC by MatheusBuss

## What issue does this PR close
Closes #245 

## Changes Proposed ( a list of new changes introduced by this PR)
Atualizar a funcionalidade do rich link preview para mostrar o preço dos produtos no título da preview

- [x] Colocar o preço na descrição, antes de começar o texto, e em negrito
- [x] Mostrar nome do autor

[Link do Figma](https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=1672%3A6427)

![image](https://user-images.githubusercontent.com/102705968/173403653-db259732-6c6d-45b2-8ca9-0e874eb3c40a.png)

2022-06-16 18:47 UTC, juramos-2020 commented
Oi Henrique achei ótima a sugestão. 
Teria como o compartilhamento do whatsapp ser igual ao do telegram? Na horizontal. A gente consegue definir isso?

2022-06-16 19:08 UTC, juramos-2020 commented
Beleza então 😉👍

2022-06-17 13:36 UTC, NeoVier approved these changes
Looks good! Have you tried using markdown syntax to make bold text? That would be surrounding text with double *: `This is **bold**`

2022-06-17 13:36 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +    end
Why not get the value directly instead of making a function?

```elixir
currency = case Commune.find_community(%{}, %{subdomain: community_subdomain}, %{}) do
...
```

2022-06-17 13:36 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +    end
Maybe it would be nicer if this and the `get_image` above were inside the `case Shop.get_product(nil, %{id: id}, nil) do`. Maybe even in another top-level function that represents the happy path that receives the product and community as inputs.

It's usually a good idea to separate branching code to "doing" code. The `case` statement is branching code. The map construction inside of it , `get_creator_name`, (the happy path of) `get_currency` and `get_image` are all "doing" code (code that *does* something).

It's also usually good to separate impure functions (we say that they produce *side-effects* in functional programming - DB access, HTTP requests/responses, writing to files, etc. - things that are non-deterministic and depend on external factors other than the code) from pure functions (functions that, given the same input, *always* return the same output - checking the length of a list and returning an item from it, slicing strings, checking if a value is present in a map, creating maps, etc.)

For example, as it is now, you need to worry about:
1. Did we successfully get the product from the DB?
2. Did we successfully get the community and it's currency from the DB?

It's not really clear to me what happens if we get the product from the DB, but we don't get the currency from the DB - Does the user see the error reason instead of the currency? Do we ignore the error?

2022-06-17 13:36 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +    end
Sorry, my FP nerd side went on a bit of a tangent here 😅. But these are tips that will help you on the long run, you don't need to worry about getting them correct 100% of the time, but these are some things that are nice to keep in mind 🙂

2022-06-20 14:54 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +    end
I think I get it. Hope to get it better in the future. I've done some refactoring and, in my eyes, it seems a lot cleaner this way. Hope this is what you meant! In any case, thanks for the tips, much appreciated!

2022-06-20 14:54 UTC, MatheusBuss commented
> Have you tried using markdown syntax to make bold text?

Also doesn't work :/

2022-06-20 16:12 UTC, lucca65 requested changes

2022-06-20 16:12 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +  @product_image "https://cambiatus-uploads.s3.amazonaws.com/cambiatus-uploads/b214c106482a46ad89f3272761d3f5b5"
maybe we could be more explicit: 
```suggestion
  @default_product_image "https://cambiatus-uploads.s3.amazonaws.com/cambiatus-uploads/b214c106482a46ad89f3272761d3f5b5"
```

2022-06-20 20:49 UTC, lucca65 requested changes

2022-06-20 20:49 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +         creator: if(creator.name, do: creator.name, else: creator.account)
```suggestion
         creator: Map.get(creator, :name) || creator.account
```

2022-06-23 20:16 UTC, lucca65 requested changes
Legal bro, essa issue não para de crescer e acho que podemos resolver essa última parte nesse PR mesmo. Tá faltando traduções adequadas para os textos que são exibidos. Podemos ter duas fontes pro idioma: 

o header `accept-language` se tiver presente ou o idioma configurado do usuário em `user.language`. Se nenhum dos dois estiver preenchido aí sim vamos pro default que é en-US

2022-06-23 20:16 UTC, lucca65 commented on lib/cambiatus_web/views/rich_link_view.ex
> +    "Vendido por #{creator} - #{md_to_txt(description)}"
Não tenho certeza se o padrão deve ser português. Temos um mecanismo de tradução colocado que você pode ver nos nossos emails. Arquivos dentro de `/priv/gettext/` e no `lib/cambiatus_web/email.ex` podem servir de referência para como fazer!

2022-06-28 23:24 UTC, lucca65 approved these changes
✨

2022-06-29 00:30 UTC, merged