Add members_since with community in GraphQl context
cambiatus/backend pull request #252
Opened 2022-06-29 17:00 UTC by MatheusBuss

## What issue does this PR close
Closes #251 and #223  

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Inserir campo `member_since` na query de usuário
- [ ] Utilizar a comunidade no contexto do GraphQl
  - [ ] Implementar o campo `member_since` com a comunidade no contexto
  - [ ] Atualizar outros campos com a comunidade no contexto

2022-06-29 17:03 UTC, MatheusBuss commented
@lucca65 como não achei uma maneira de fazer implementar o campo sem informar a comunidade duas vezes na query decidi já implementar o contexto nos plugs do absinthe também. Pensei em aproveitar e dar uma atualizada nas outras queries que também utilizam o `communityId` no mesmo PR.

2022-06-29 17:11 UTC, lucca65 commented
+1! é um PR bem de refactor mesmo… manda bala!

2022-06-30 17:46 UTC, MatheusBuss commented
@lucca65 até o momento eu fui retirando os argumentos `communityId` das queries e pegando sempre do contexto. Mas fiquei me perguntando se não vale a pena manter esse argumento em algumas queries. Mais com o pensar de um admin mesmo, que pdoe selecionar em qual comunidade fazer alterações ou queries.

-------

E outra, em `account_types` têm algumas queries de transferência e contribuições que permitem inserir o `communityId` como filtro em uma comunidade específica. Pensei em transformar esse campo em um booleano pra filtrar na comunidade atual.

2022-06-30 17:54 UTC, lucca65 commented
> @lucca65 até o momento eu fui retirando os argumentos communityId das queries e pegando sempre do contexto. Mas fiquei me perguntando se não vale a pena manter esse argumento em algumas queries. Mais com o pensar de um admin mesmo, que pdoe selecionar em qual comunidade fazer alterações ou queries. 

Mas nesse caso não seria mais fácil ter um seletor de comunidade na query, que altera o Community Domain e pronto?

2022-06-30 17:55 UTC, lucca65 commented
> E outra, em account_types têm algumas queries de transferência e contribuições que permitem inserir o communityId como filtro em uma comunidade específica. Pensei em transformar esse campo em um booleano pra filtrar na comunidade atual.

em qual? bati o olho rapidinho no account_types e não achei

2022-06-30 18:02 UTC, MatheusBuss commented
> > E outra, em account_types têm algumas queries de transferência e contribuições que permitem inserir o communityId como filtro em uma comunidade específica. Pensei em transformar esse campo em um booleano pra filtrar na comunidade atual.
> 
> em qual? bati o olho rapidinho no account_types e não achei

`lib/cambiatus_web/schema/account_types.ex - 216`

```elixir
    field(:contribution_count, non_null(:integer)) do
      arg(:community_id, :string,
        description:
          "Optional community filter, filling this will get only contributions from this community"
      )
```

-----

`lib/cambiatus_web/schema/account_types.ex - 232`

```elixir
    field(:claims, non_null(list_of(non_null(:claim)))) do
      arg(:community_id, :string,
        description:
          "Optional community filter, filling this will get only claims from this community"
      )

      resolve(dataloader(Cambiatus.Objectives))
    end
```

-----


`lib/cambiatus_web/schema/account_types.ex - 254`

```elixir
  input_object :transfer_filter do
    field(:date, :date, description: "The date of the transfer in `yyyy-mm-dd` format.")

    field(:direction, :transfer_direction,
      description: "If the user is receiving or sending the transaction"
    )

    field(:community_id, :string,
      description: "optional filter for querying transfers from a community"
    )
  end
```

-----

Acho que são esses

2022-06-30 19:52 UTC, lucca65 commented on lib/cambiatus_web/plugs/get_origin.ex
> +            conn
maybe the plug should fail if we can't assign them to a community... not sure how it would fit on our pipeline and error tracking but it makes sense in a first view

2022-07-08 02:57 UTC, lucca65 requested changes
Uma olhada superficial, logo tento retomar esse review

2022-07-08 02:57 UTC, lucca65 commented on lib/cambiatus/accounts/accounts.ex
> +      )
o que acha de usar a notação de função? Olha como ficaria:


```elixir 
Network
|> Network.by_community(community.symbol)
|> Network.by_user(user.account)
|> select([n], n.created_at)
|> Repo.one()
|> case do
  nil → 
    {:error, "Could not find user in community"}
  
  member_since →
    {:ok, member_since}
end

2022-07-08 02:57 UTC, lucca65 commented on lib/cambiatus_web/channels/user_socket.ex
> +      |> Map.take(["Authorization", "community-domain"])
acho que vale mais a pena fazer o take dentro da função `build_context`

2022-07-08 02:57 UTC, lucca65 commented on lib/cambiatus_web/channels/user_socket.ex
> +      |> Map.take(["Authorization", "community-domain"])
talvez até aplicar Pattern matching se ficar legal

2022-07-08 02:57 UTC, lucca65 commented on lib/cambiatus_web/resolvers/accounts.ex
> +      |> Map.get(:subdomain)
Precisamos adicionar uma query pra saber dessa informação? To meio descontextualizado mas acredito que continuaremos com o Domain no contexto não? 

Se for o caso de não ter mais, será que não fazemos essa query novamente de maneira reversa no sign_in?

2022-07-08 12:39 UTC, MatheusBuss commented on lib/cambiatus/accounts/accounts.ex
> +      )
Parece bem melhor mesmo :smiley:

2022-07-08 13:05 UTC, MatheusBuss commented on lib/cambiatus_web/channels/user_socket.ex
> +      |> Map.take(["Authorization", "community-domain"])
Fiz um pattern match com diversas cláusulas pra função `build_context`, acho que assim fica mais fácil de manter o código, mas podemos mudar se não era bem isso que querias dizer.

2022-07-08 14:39 UTC, lucca65 commented on lib/cambiatus_web/resolvers/accounts.ex
> +      |> Map.get(:subdomain)
acho que se decidirmos deixar carregada a memória no contexto, podemos modificar as funções que usam isso. Nesse exemplo do sign_in:

```elixir
def sign_in(account, password, domain: domain) do
    Sentry.Context.set_extra_context(%{account: account, domain: domain})

    with {:ok, %Community{} = community} <- Commune.get_community_by_subdomain(domain),
         %User{} = user <- Accounts.get_user(account),
         true <- Accounts.verify_pass(account, password) do
      case {community.auto_invite, Commune.is_community_member?(community.symbol, account)} do
        # Community has auto invite and user is not in yet
        {true, false} ->
          {:ok, _txid} = netlink(user, community)
```

Fazemos a query já, então se tivesse pronta economizaríamos, mas do jeito que tá agora, estamos fazendo duas query quando poderíamos fazer só uma, oq acha?

2022-07-08 15:49 UTC, MatheusBuss commented on lib/cambiatus_web/resolvers/accounts.ex
> +      |> Map.get(:subdomain)
Não entendi direito a parte de memória no contexto. Essa questão de não repetir a query eu venho fazendo em alguns lugares, pelo jeito deixei passar aí no sign_in :sweat_smile:.

De qualquer jeito, sobre manter o `domain` no contexto, pensei em mudar essa linha do `get_origin.ex`:
```elixir
Absinthe.Plug.assign_context(conn, current_community: current_community)
```
Para:
```elixir
Absinthe.Plug.assign_context(conn, %{domain: domain, current_community: current_community})
```
Dessa maneira ele coloca os dois campos (`domain` e `current_community`), mas só depois de passar nos testes procurando a comunidade

2022-07-11 21:40 UTC, lucca65 approved these changes
ganhamos testes extras, consistencia e mais simplicidade, abstraindo domínio de comunidade selecionada! Show!

2022-07-12 13:36 UTC, NeoVier commented
Precisamos atualizar o frontend (https://github.com/cambiatus/frontend/issues/782) pra usar o novo schema antes de mergear esse PR, certo?

2022-07-13 18:56 UTC, merged