Enhancement/email unsubscribing without password
cambiatus/backend pull request #258
Opened 2022-07-13 17:54 UTC by MatheusBuss

## What issue does this PR close
Closes #204 

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Add authenticated link to sent emails
  - [X] Generate token for user authentication
  - [ ] Send each user their own token
- [ ] Authenticate user when using the provided link
  - [ ] Ensure that the authentication is only valid for unsubscribing to emails
- [ ] Implement one click functionality for unsubscription
- [ ] Handle verification for a page specifically made for unsubscribing

2022-07-13 20:15 UTC, lucca65 commented on lib/cambiatus_web/auth_token.ex
> +  end
Maybe you can match on the function itself

```elixir
def auth_salt("user"), do: Application.get_env(:cambiatus, :auth_salt)
def auth_salt("email"), do: Application.get_env(:cambiatus, :auth_salt_email)
```

2022-07-13 20:15 UTC, lucca65 commented on lib/cambiatus_web/controllers/unsubscribe_controller.ex
> +      })
It doesn't make sense for Resolvers and Controllers to be talking. They are from different pipelines of how we handle an Request. Resolvers will be used by GraphQL/Absinthe to sort our their own scope.

All other requests should be handled in they own way. Not only this decouples our logic for each API type (REST has one structure and GraphQL has another. If we implement RTC it would use another) but it also gives us hints on our own architecture. 

If we find ourselves having to share logic between web adapters, we surely are having business rules inside our web layer. 

We should try to keep them separate as it will help us grow more easily. Necessary bureaucracy. Hit me up on slack if you need to talk more about this bro!

2022-07-13 20:28 UTC, MatheusBuss commented on lib/cambiatus_web/auth_token.ex
> +  end
Definitively way better

2022-07-13 20:29 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/unsubscribe_controller.ex
> +      })
Yeah, it makes sense. I wasn't too sure of how to implement this. It made sense to re utilize what we already had, but the way I made really didn't feel right. I guess I'll be doing it via changeset then.

2022-07-13 20:36 UTC, lucca65 commented on lib/cambiatus_web/controllers/unsubscribe_controller.ex
> +      })
Well, I can see two scenarios:

1. We do change sets inside the resolver. If we do this, that's wrong, we should send all the necessary data to our `lib/cambiatus/` modules to do so
2. We already update preferences in our business layer. In that case you can use the function

Ideally we are able to hook up any existing feature into our business layer even if we are rebuilding the API from scratch

2022-07-14 01:06 UTC, lucca65 commented on lib/cambiatus_web/controllers/unsubscribe_controller.ex
> +      Cambiatus.Accounts.update_user(current_user, %{subject => false})
Maybe an alias would make this easier to read?

2022-07-21 13:17 UTC, MatheusBuss commented
Acredito que é mais ou menos isso mesmo, mas tem algumas coisas que ainda poderiam ser feitas:
* Adicionar um teste para o corpo html do email
* Verificar se o one-click unsub está funcionando
------
Outra coisa que vi durante o desenvolvimento desse PR que poderíamos fazer: O gmail possui o que ele chama de [actions](https://developers.google.com/gmail/markup/actions/actions-overview), que são botões ao dar hover no email que fazem alguma coisa, como o exemplo do sentry abaixo. Quem sabe poderia ser algo a fazer também.
![image](https://user-images.githubusercontent.com/102705968/180222801-e16dcbfd-c491-44c7-be66-77cd3cea728f.png)

2022-07-25 14:26 UTC, NeoVier approved these changes
Sorry for the delay 🏃‍♂️ 

I have a few comments, but it looks good overall!

2022-07-25 14:26 UTC, NeoVier commented on lib/cambiatus_web/email.ex
>        new()
I wonder if this is going to work... Looking at the SES console, we have limits on how many emails we can send (the main worry is emails/second):
![image](https://user-images.githubusercontent.com/39280468/180795508-a414fe91-964c-4d88-bfb5-4b125684ede2.png)

Maybe @lucca65's idea of sticking the emails into a queue would be nice to avoid getting rate limited

2022-07-25 14:26 UTC, NeoVier commented on lib/cambiatus_web/auth_token.ex
> +    Phoenix.Token.verify(Endpoint, auth_salt(authorization), token, max_age: 365 * 24 * 3_600)
I remember we talked about this before, but I don't really remember what we settled on, so...

Should we worry about setting a lower `max_age`, or invalidating it after one use (or something like that) for email tokens? I don't think it's a huge security issue, but if there's someone inspecting the network traffic, they can get the user's token and act in their behalf

2022-07-25 14:26 UTC, NeoVier commented on lib/cambiatus_web/schema/middleware/email_special_authenticate.ex
> +          {:error, "Please sign in firt or use a valid unsubscription link"}
```suggestion
          {:error, "Please sign in first or use a valid unsubscription link"}
```

2022-07-25 14:26 UTC, NeoVier commented on lib/cambiatus_web/views/email_view.ex
>  end
Should we still keep this file if it's empty? Maybe I'm missing some elixir magic 😅

2022-07-25 14:26 UTC, NeoVier commented on lib/cambiatus_web/email.ex
> +  end
Maybe it would make more sense to just return the url (without the brackets), and include the brackets in the calling code, to be a bit more reusable

```suggestion
  def one_click_unsub(member, community, subject) do
    token = AuthToken.sign(member, "email")

    "https://#{community.subdomain.name}/api/unsubscribe/#{subject}/#{token}"
  end
```

2022-07-25 14:31 UTC, NeoVier commented
O botão de unsubscribe apareceu pra mim (enviando para um email do gmail, vendo pelo app Mail da Apple). Cliquei nele, apareceu uma caixa de confirmação, e quando eu aceitei não aconteceu nada (as opções de email continuam habilitadas). Tentei de novo, mas agora o botão não aparece mais. Talvez o botão não funcionou por não ser confiável ainda ou algo assim

2022-07-25 17:47 UTC, lucca65 requested changes

2022-07-25 17:47 UTC, lucca65 commented on lib/cambiatus_web/auth_token.ex
> +    Phoenix.Token.verify(Endpoint, auth_salt(authorization), token, max_age: 365 * 24 * 3_600)
If the page/token is only for changing email preferences, then I think its ok to have a big invalidation window. But if its for regular usage, it should be shorter for sure. Something around the week values. 

I'm not sure if Phoenix automatically updates the token validity based on usage (ie, if I keep using the app daily, it don't ever invalidate)

2022-07-25 17:47 UTC, lucca65 commented on lib/cambiatus_web/email.ex
> +    |> header("List-Unsubscribe-Post", "List-Unsubscribe=One-Click")
maybe this and `set_language` could be a default header? Maybe with some function pattern matches to ensure every case (transfer, claim) is met

2022-07-25 17:47 UTC, lucca65 commented on lib/cambiatus_web/email.ex
>        new()
+1, maybe we can actually create an issue to change this to a job queue, where we can configure sending limits. As we talked on Friday, I think this should be done separately, as this will be somewhat of a (very needed) refactor. 

This is a good sign. No serious production project lives on without some kind of background processing part!

2022-07-25 17:47 UTC, lucca65 commented on lib/cambiatus_web/email.ex
> +  end
+1

2022-07-25 17:47 UTC, lucca65 commented on lib/cambiatus_web/email.ex
> +    |> Enum.map_join("/", &to_string/1)
had no idea a `map_join` existed kkkk

2022-07-25 18:38 UTC, MatheusBuss commented on lib/cambiatus_web/email.ex
> +    |> Enum.map_join("/", &to_string/1)
Credo actually pointed it out to me, so I just followed :sweat_smile:

2022-07-25 18:45 UTC, MatheusBuss commented on lib/cambiatus_web/email.ex
> +    |> header("List-Unsubscribe-Post", "List-Unsubscribe=One-Click")
I agree with @NeoVier to create a function to compose emails, this way it's more standardized in code ans also easiser to create new emails. Maybe it could deal with everything that refers to community and recipient user.

2022-07-25 19:04 UTC, MatheusBuss commented on lib/cambiatus_web/views/email_view.ex
>  end
Yeah, Phoenix gets really unhappy without this one.

2022-07-25 19:06 UTC, MatheusBuss commented
> If the page/token is only for changing email preferences, then I think its ok to have a big invalidation window. But if its for regular usage, it should be shorter for sure. Something around the week values.

This is something that could be done on #262. maybe we could have it be two weeks. Whats do you think @lucca65 and @NeoVier?

2022-07-25 19:14 UTC, MatheusBuss commented on lib/cambiatus_web/auth_token.ex
> +    Phoenix.Token.verify(Endpoint, auth_salt(authorization), token, max_age: 365 * 24 * 3_600)
This is something that could be done on https://github.com/cambiatus/backend/pull/262. maybe we could have it be two weeks. Whats do you think @lucca65 and @NeoVier?

2022-07-25 19:17 UTC, lucca65 commented
thats ok for me!

2022-07-25 19:19 UTC, NeoVier commented on lib/cambiatus_web/auth_token.ex
> +    Phoenix.Token.verify(Endpoint, auth_salt(authorization), token, max_age: 365 * 24 * 3_600)
Sure, I think that's ok

2022-07-25 19:32 UTC, MatheusBuss commented on lib/cambiatus_web/email.ex
>        new()
Created #263

2022-07-26 17:07 UTC, MatheusBuss commented on lib/cambiatus_web/email.ex
> +    |> Enum.map_join("/", &to_string/1)
I'm looking into this. There is the [Cldr](https://hexdocs.pm/ex_cldr/1.6.4/readme.html) library that is meant to handle this type of localization. I think it's worth it to spend some time to get it working beacause in addition to formatting dates it can localize other data such as currencies and numbers. This then could be used by future issues, such as #198.

2022-07-26 17:42 UTC, NeoVier commented on lib/cambiatus_web/email.ex
> +    |> Enum.map_join("/", &to_string/1)
If you feel like this is going to take some bigger effort, it may be worth creating a new issue and dealing with it separately, since that's not really the focus of this PR, but that's your call 😄

2022-07-26 18:05 UTC, MatheusBuss commented on lib/cambiatus_web/email.ex
> +    |> Enum.map_join("/", &to_string/1)
Should be fine for this one. Already gonna test it on staging

2022-07-26 18:30 UTC, MatheusBuss commented on lib/cambiatus_web/email.ex
> +    |> Enum.map_join("/", &to_string/1)
![image](https://user-images.githubusercontent.com/102705968/181084063-ccecb510-3cfa-4bfe-830c-24a3ab6f542f.png)
Seems like it works

2022-07-26 19:54 UTC, lucca65 approved these changes
✨

2022-07-26 19:55 UTC, merged