Privacy/security enhancement
cambiatus/backend pull request #262
Opened 2022-07-25 18:58 UTC by MatheusBuss

## What issue does this PR close
Closes #228 

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Remove potential XSS flaw in rich link controller
- [ ] Remove Directory traversal in upload_controller

2022-07-27 16:57 UTC, MatheusBuss commented
@lucca65 this should deal with most of the security concerns raised by sobelow. The only one remaining refers to the upload controller, which I'm not sure how to solve. Maybe we could discuss this one a bit better.

2022-07-28 23:02 UTC, lucca65 requested changes
Bro, this looks great! New tests for auth token, new token invalidation window and an automated tool.

The only thing I think its missing is adding sobelow to our CI, making our builds fail if new security issues arise

2022-07-28 23:02 UTC, lucca65 commented on lib/cambiatus_web/auth_token.ex
> +    Phoenix.Token.verify(Endpoint, auth_salt(authorization), token, max_age: 14 * 24 * 3_600)
great!

2022-07-28 23:02 UTC, lucca65 commented
Oh i've also removed it from draft state, hope you don't mind. It was already looking ready

2022-07-29 13:58 UTC, MatheusBuss commented
> The only thing I think its missing is adding sobelow to our CI, making our builds fail if new security issues arise

Didn't realize that `mix check` was different from the CI :sweat_smile:. Should be working now.

2022-07-29 14:33 UTC, lucca65 approved these changes
Looks like our setup is complete! the build is failing though

2022-07-29 14:53 UTC, MatheusBuss commented
It's failling because of the upload controller. I'm fairly certain that we can ignore this one but I wanted to double check it with someone.

It happens because on `lib/cambiatus_web/controllers/upload_controller.ex` - line 14 there's a `File.read!` and this function could be used to read other files in the production machine.

However I don't think that this attack is possible. The file beign read is created by Phoenix as a temp file when an image is uploaded (and the user has no input about this). So this function can only run when a file is uploaded and then Phoenix generates the temp file. The question is if there's no other way this function can be executed. On the tests I ran no code runs if something other than a file is passed to the api.

Another potential concern is [steganography](https://www.sentinelone.com/blog/hiding-code-inside-images-malware-steganography/).

2022-08-04 14:47 UTC, lucca65 commented
Pois é. O ideal é buscar por outras maneiras de fazer isso. Se não houver, podemos ignorar a analise: https://github.com/nccgroup/sobelow#false-positives

Como isso tá no CI agora, os Merges vão ser bloqueados se não passar. Ou seja, não é possível simplesmente aprovar o PR e ignorar, como dev tens que entregar uma build que é aprovada pelo CI.

2022-08-04 14:47 UTC, lucca65 approved these changes

2022-08-04 19:09 UTC, merged