Fix/rich link empty bio
cambiatus/backend pull request #265
Opened 2022-07-28 01:14 UTC by MatheusBuss

## What issue does this PR close
Closes #264 

## Changes Proposed ( a list of new changes introduced by this PR)
Fill rich link description field when the user has no bio

2022-07-28 01:19 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +        {:error, "Category not found"}
@lucca65 maybe we should make `Cambiatus.Shop.get_category` consistent with other get functions, as in make it return either `{:ok, category}` or `{:error, reason}`

2022-07-28 01:19 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +  end
Since I'm revisiting this, it could be a good idea to set the community language properly. We could make it get the community creator language or have some way to set a default language for every community.

2022-07-28 15:27 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           currency: String.slice(community.symbol, 2, 7),
The current implementation actually wouldn't work for this community I have: https://precisionthree.staging.cambiatus.io/dashboard. The symbol is 7 characters long (`3,THREEPR`)

2022-07-28 16:15 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           currency: String.slice(community.symbol, 2, 7),
This makes a lot of sense actually. I thought we had some limit to the symbol string. Good catch!

2022-07-28 17:33 UTC, NeoVier approved these changes
✨

2022-07-28 17:35 UTC, NeoVier commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +           currency: String.slice(community.symbol, 2, 7),
We do have some limits, I think it must be 3 <= length <= 7. But we don't need to worry about that with the `String.split` method

2022-07-28 23:12 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +        {:error, "Category not found"}
+1, this is not consistent at all in our contexts. I do think we need to aim for consistency

2022-07-28 23:14 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +  end
One thing to keep in mind is that community creation happens on the blockchain, and its synced up to our database. This means that we don't have the creators language at our context, unless we modify the contract to add this extra information. IMO, its not worth the trouble, at least for now. 

I mean, at some point we will need to walk you through contract modifications and how to respond to that in our backend. We have #148 that seems like a nice spot for this exercise

2022-07-28 23:19 UTC, lucca65 requested changes
I think we got the wrong concept here on this issue bro. We don't have community information over HTTP Rest, only given our graphql Stuff. 

Think about it. The GraphQL client is the frontend, but the user of our Rich Link is the scrapping bots and Apps previewers. They don't do that using GraphQL, but rather plain json/http. 

Unless I'm missing something this is not going to fix it for our rich link use cases

2022-07-28 23:19 UTC, lucca65 commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +    context = conn.private[:absinthe][:context]
This don't make sense, absinthe context is relevant when we receive GraphQL over HTTP requests. Controllers don't handle that. 

Remember that we have two APIs on our backend today: GraphQL and Rest. We should consider them completely separate.

2022-07-29 03:00 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +    context = conn.private[:absinthe][:context]
Oops, forgot about that, sorry. It was just bothering me that the community is already stored in memory and the controller had to fetch it again.

I did some refactoring to place the current community also into conn itself, this way it's not reliant on GraphQL. But this does imply in having the same information passing around the app twice on every call.

2022-07-29 03:16 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +  end
My idea for this case was to get the user from the creator field in the Community struct and use this language. It's not perfect, but it's something

2022-07-29 12:58 UTC, MatheusBuss commented on lib/cambiatus_web/controllers/rich_link_controller.ex
> +        {:error, "Category not found"}
:heavy_check_mark: Done

2022-07-29 18:16 UTC, lucca65 approved these changes
✅

2022-08-01 12:46 UTC, merged