Script para atualização de campos com string vazia
cambiatus/backend pull request #270
Opened 2022-08-02 18:54 UTC by MatheusBuss

## What issue does this PR close
Closes #266 

## Changes Proposed ( a list of new changes introduced by this PR)
Criar script para detectar valores `""` já existentes na db e atualizá-los para `nil`

## How to test ( a list of instructions on how to test this PR)
1. Procurar na db por valores com `''`
2. Executar `iex -S mix priv/repo/null_string.exs`
3. Verficar se os valores foram alterados para `NULL`

2022-08-03 04:21 UTC, lucca65 commented on priv/repo/null_strings.exs
> +IO.puts("Replacing empty strings with null")
pode especificar no nome do arquivo e na descrição em qual tabela/entidade está fazendo isso?

2022-08-03 13:09 UTC, MatheusBuss commented on priv/repo/null_strings.exs
> +IO.puts("Replacing empty strings with null")
São algumas tabelas. Talvez seja melhor deixar alguns comentários pra especificar isso. Quem sabe pro título/puts podemos colocar algo tipo "Replace empty string ingested by the event-source with nil". Pro nome do arquivo poderia ser "empty_strings_to_nil.exs".

2022-08-04 14:51 UTC, lucca65 commented on priv/repo/null_strings.exs
> +IO.puts("Replacing empty strings with null")
A sugestão que você deu é melhor, não acho que precisamos focar em ter nomes pequenos para o script. Gosto de pensar que tudo isso é para nossos futuros eus principalmente e quanto mais rápido dermos contexto para nós mesmos, melhor. 

No arquivo, nesse `IO.puts/1` acho melhor colocar o nome de todas as tabelas afetadas. Isso vai aparecer nos logo também então algo como `empty strings with null` não dá pra entender. Afinal não é para todas as empty strings, mas para algumas, em algumas tabelas

2022-08-04 17:20 UTC, MatheusBuss commented
São esses os campos que encontrei. Ainda não mudei todos no event-source. Se batermos o martelo aqui já atualizo o PR de lá também!

2022-08-04 21:53 UTC, NeoVier approved these changes
Não consigo pensar em mais nenhum campo, me parece ok

2022-08-08 18:58 UTC, lucca65 approved these changes
Looks nice as well!

2022-08-08 18:59 UTC, lucca65 requested changes
Actually thinking better, we should add database constraints for those fields

2022-08-08 18:59 UTC, lucca65 commented
Because if not, we may end up with the same problem in the future, a simple migration adding this constraint should be enough to make sure we will not end up with a dirty db

2022-08-08 20:56 UTC, MatheusBuss commented
> Because if not, we may end up with the same problem in the future, a simple migration adding this constraint should be enough to make sure we will not end up with a dirty db

Makes a ton of sense. I've added some simple constraints on the fields we discussed.

2022-08-08 20:58 UTC, lucca65 approved these changes
nice! I think this is future proof now!

2022-08-08 21:08 UTC, merged