Add content-type information when uploading to S3
cambiatus/backend pull request #75
Opened 2020-09-07 13:59 UTC by RodrigoLeiteF

----

## What issue does this PR close
Closes #73

## Changes Proposed (a list of new changes introduced by this PR)
1. Adds content type information to S3 uploads

## How to test ( a list of instructions on how to test this PR)
1. Run `mix test`
2. Upload a file to the `/upload` endpoint, send a request to the returned URL and confirm the Content-Type header is correct

2020-09-07 18:02 UTC, amiskov requested changes
Tests are passed on my side, but I couldn't check the actual uploading due to my dev setup. Couldn't make it work with AWS on my localhost 🤷🏻‍♂️

The code itself looks good to me, the only one request is moving the test for authorization to the related branch/PR.

2020-09-07 19:45 UTC, RodrigoLeiteF commented on test/cambiatus_web/schema/resolvers/accounts_test.exs
> +    test "fails to create a user when it already exists", %{conn: conn} do
Good catch

2020-09-07 21:33 UTC, lucca65 requested changes
I've deployed this branch to our dev env and it still don't work with mobile phones. not sure why

2020-09-21 16:45 UTC, RodrigoLeiteF commented
This should be merged anyway. It doesn't hurt to send the appropriate metadata for images

2020-09-22 11:30 UTC, amiskov approved these changes

2020-09-22 20:39 UTC, lucca65 commented
I'm not sure of that, have you tested it with Apple Devices?

2020-09-23 17:09 UTC, RodrigoLeiteF commented
> I'm not sure of that, have you tested it with Apple Devices?

It won't fix the issue we're having with XES but either way it's beneficial to send the appropriate Content-Type header when working with images. It's part of the HTTP spec after all.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

2020-09-24 10:59 UTC, amiskov commented
> the issue we're having with XES

@lucca65 @RodrigoLeiteF is there any description of the issue? Maybe I can help with the investigation?

2020-09-24 15:02 UTC, lucca65 commented
We are pushing a lot of code without tests lately. I keep finding issues of code without good enough quality that brings more problems than it solves. I feel like even something small can become a headache because we don't test it enough. Like keep from testing on apple devices is a problem. Because a fraction of our user base uses it and 2 devs also use it. I might not hurt, but the problem with XES persist because of that same way of thinking. Lets merge this since we are in a heavy testing phase. But the overall quality of our deliveries is really bad and should be improved

2020-09-24 15:02 UTC, lucca65 approved these changes

2020-09-24 15:02 UTC, merged