Add mutation for update/create KYC fields for the user
cambiatus/backend pull request #77
Opened 2020-09-10 16:14 UTC by amiskov

## What issue does this PR close
Closes #60 

## Changes Proposed (a list of new changes introduced by this PR)
Create a mutation (or mutations) for adding and updating user KYC information.

## How to test (a list of instructions on how to test this PR)
TBD.

2020-09-11 16:01 UTC, lucca65 requested changes

2020-09-11 16:01 UTC, lucca65 commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :update_or_create_address, :address do
we could call this upsert, we already use this term in the contracts

2020-09-11 16:45 UTC, amiskov commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :update_or_create_address, :address do
Oh, nice! Didn't know this word :)

2020-09-11 18:17 UTC, lucca65 commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :update_or_create_address, :address do
made up dev word 😛

2020-09-14 08:35 UTC, merged

2020-09-14 08:41 UTC, amiskov commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :update_or_create_address, :address do
@lucca65 I decided to go with`upsert` as you suggested! We already use this word even in the frontend for Actions. The [changes](https://github.com/cambiatus/backend/pull/77/commits/343c738aaf4d2922bd7d99f33f4c5a6bdf65ccd7) were only in naming, so I decided not to ask you about re-reviewing and just merged this PR.