User KYC data deletion mutation
cambiatus/backend pull request #78
Opened 2020-09-10 21:24 UTC by victorgdev

## What issue does this PR close
Closes #58 

## Changes Proposed ( a list of new changes introduced by this PR)
KYC user data deletion mutation

## How to test ( a list of instructions on how to test this PR)

2020-09-11 16:25 UTC, amiskov commented on lib/cambiatus/kyc/kyc.ex
> +    Repo.delete(params)
I guess there should be something like this:

```elixir
kyc = Repo.get_by(KycData, params.account_id)
Repo.delete(kyc)
```

First, we get the actual KYC record which we want to delete and then pass it to the function, which handles the actual deleting from the DB.

2020-09-11 16:28 UTC, amiskov commented on lib/cambiatus/kyc/kyc.ex
> +  def kyc_data_deletion(params) do
Oh, and there's a common convention to give function names starting with verbs: `delete_kyc` or something like this.

2020-09-11 17:38 UTC, lucca65 requested changes

2020-09-11 17:38 UTC, lucca65 commented on lib/cambiatus_web/schema/kyc_types.ex
> +  end
you can just send the account here

2020-09-14 10:09 UTC, amiskov commented on lib/cambiatus_web/schema/kyc_types.ex
> +  end
Yep, that's enough for us to have `account_id` to find the KYC record which we want to delete:
```elixir
  input_object :kyc_data_deletion do
    field(:account_id, non_null(:string))
  end
```

The actual mutation could look like this:

```graphql
mutation ($input: KycDataDeletion!) {
  deleteKyc(input: $input) {
    document
    userType
    # some info from the deleted KYC record
    # that we may need on the frontend
  }
}

# Input
{
  "input": {
    "accountId": "andreymiskov"
  }
}
```

2020-09-15 08:47 UTC, amiskov requested changes

2020-09-15 08:47 UTC, amiskov commented on lib/cambiatus_web/schema/kyc_types.ex
> +  end
Since these inputs are the same, I think it's ok to use only `:kyc_deletion_input` for both KYC and Address deletion.

2020-09-15 08:47 UTC, amiskov commented on lib/cambiatus/kyc/kyc.ex
> +    kyc = Repo.get_by(KycData, params.account_id)
Unfortunately, this line won't work. Here's a little explanation.

After the evaluation, `params.account_id` becomes a string like `"victorgoncal"`. But we have to explain what `"victorgoncal"` is to the function `get_by`. So instead of a string, it [should be a map](https://hexdocs.pm/ecto/Ecto.Repo.html#c:get_by/3) like this: `%{account_id: "victorgoncal"}`.

If we check what is stored in `params` then we will see that it's lust this map, so this will work fine:

```elixir
kyc = Repo.get_by(KycData, params)
```

BTW, you can use [`IO.inspect(params)`](https://hexdocs.pm/elixir/IO.html#inspect/2) to check what is stored in variables. The output will be visible in the terminal where the Phoenix is running.

2020-09-15 08:47 UTC, amiskov commented on test/cambiatus_web/schema/resolvers/kyc_test.exs
> +      new_kyc = delete(:kyc_data, %Plug.Conn{})
This line is unnecessary. The GraphQl mutation itself will delete the KYC record.

2020-09-15 08:47 UTC, amiskov commented on test/cambiatus_web/schema/resolvers/kyc_test.exs
> +      mutation ($input: KycDeleteInput!) {
Actually, your input object has the name `KycDeletionInput`(the `:kyc_deletion_input` symbol from `lib/cambiatus_web/schema/kyc_types.ex`).

2020-09-15 08:47 UTC, amiskov commented on test/cambiatus_web/schema/resolvers/kyc_test.exs
> +          country_id
The `:kyc_data` object had `country` field, not `country_id`. And the country itself is also an object with fields, so this is the right way to get the country id: `country { id }`.

2020-09-15 08:47 UTC, amiskov commented on test/cambiatus_web/schema/resolvers/kyc_test.exs
> +      assert deleted_kyc["user_type"] == new_kyc.user_type
Instead of `new_kyc` you should use just `kyc`, which you created earlier on line `145`:

```elixir
assert deleted_kyc["user_type"] == kyc.user_type
```

Here you check if your original `kyc` you created has the same fields as the record you deleted with the mutation.

2020-09-15 08:47 UTC, amiskov commented on test/cambiatus_web/schema/resolvers/kyc_test.exs
> +      assert deleted_kyc["is_verified"] == new_kyc.is_verified
Actually, it's not necessary to check all the fields. You can check several most important ones, like `user_type`, `document_type`, and `document`.

2020-09-15 08:47 UTC, amiskov commented on test/cambiatus_web/schema/resolvers/kyc_test.exs
> +      new_address = delete(:address, %{account: nil})
Comments for KYC test are also related to the Address test.

2020-09-15 12:17 UTC, victorgdev commented on lib/cambiatus/kyc/kyc.ex
> +    kyc = Repo.get_by(KycData, params.account_id)
🙌 You're the man!! Tks!

2020-09-15 14:31 UTC, amiskov approved these changes
Looks good to me!

2020-09-15 15:27 UTC, lucca65 requested changes

2020-09-15 15:27 UTC, lucca65 commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field(:account_id, non_null(:string))
`account_id` don't make a lot of sense, in some places its called only account (profile object, sign_up_input) etc. Since the account is already an ID this is redundant

2020-09-15 15:29 UTC, lucca65 requested changes

2020-09-15 15:29 UTC, lucca65 commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :delete_kyc, :kyc_data do
I don't think the return type here is valid, if we return the deleted KYC it will not make no sense, we should return an status. See sign up for an example:

```elixir

  object :sign_up do
    field(:status, non_null(:sign_up_status))
    field(:reason, non_null(:string))
  end
```

https://github.com/cambiatus/backend/blob/0e7d9c82c59a78ca3790cb020705b0426fcc2115/lib/cambiatus_web/schema/account_types.ex#L72

2020-09-15 18:52 UTC, lucca65 requested changes

2020-09-15 18:52 UTC, lucca65 commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :delete_kyc, :kyc_data do
it is still returning `:kyc_data` and not the status. Please test it first!

2020-09-15 21:32 UTC, lucca65 requested changes
Nice! we are getting there. Still one problem though. If the frontend asks to delete KYC for a user that don't have it (it may happen due to having two sessions opened) the backend crashes. It also crashes if we inform an account that don't exist.

we can use the status to inform the success of failure along with a message. You can always check the sign up mutation for an example on how to do that!

I'm pushing you to make this feature complete @victorgdev! I'm sure you can nail it! game on! 💪

2020-09-16 10:42 UTC, amiskov commented on lib/cambiatus_web/schema/kyc_types.ex
> +    field :delete_kyc, :kyc_data do
@victorgdev @lucca65 That's why it's always better to discuss the API before the actual implementation :)

@lucca65 how cool is that that we could have a code snippet with a line number just pasting the URL for the line of code in the GitHub comment like you did! I'll use it all the time from now on :)

2020-09-16 22:07 UTC, lucca65 requested changes

2020-09-16 22:07 UTC, lucca65 commented on lib/cambiatus_web/resolvers/kyc.ex
> +      _ ->
maybe we should be sure it worked with another match -> `{:ok, _}`

2020-09-16 23:04 UTC, victorgdev commented on lib/cambiatus/kyc/kyc.ex
> +      nil -> {%KycData{is_verified: false}}
We'll make the changes right away

2020-09-17 14:28 UTC, lucca65 approved these changes
+1!

2020-09-17 14:35 UTC, merged