Adds acct foreign-constraint to kyc & address changeset
cambiatus/backend pull request #87
Opened 2020-09-29 20:10 UTC by victorgdev

## What issue does this PR close
Closes #82 

## Changes Proposed ( a list of new changes introduced by this PR)
- Adds the account_id foreign constraint to the KYC and Address changeset

## How to test ( a list of instructions on how to test this PR)
- Go to the GraphiQL Playground 
- Run the upsertKYC and/or upsertAddress mutations

**Examples For Testing**

```
// UpsertKYC

mutation {
    upsertKyc( input: 
      { accountId: "andreymisk",  // account does not exist
      countryId: "1", 
      document: "1231231231", 
      documentType: "nite", 
      phone: "11948340013", 
      userType: "natural"})
      { phone
      country { name } }
}

// UpsertAddress

mutation {
   upsertAddress( input: 
      { accountId: "andreymisk",
      cityId: "1",
      countryId: "1", 
      neighborhoodId: "1",
      number: "123",
      stateId: "1",
      street: "Elm street",
      zip: "10101"})
      { country { name } }
}
```

## Mutation Results
BEFORE
![image](https://user-images.githubusercontent.com/53874965/94610234-f6308d80-026d-11eb-821a-469f55a172a7.png)

AFTER
![image](https://user-images.githubusercontent.com/53874965/94610278-0ea0a800-026e-11eb-966f-4d76fc1e5649.png)

2020-09-29 20:16 UTC, victorgdev commented
@lucca65 , @RodrigoLeiteF, @amiskov  can I get some feedback on the solution, only fixed the constraint error and not the error messaging for the frontend handling, which is related to [this issue](https://github.com/cambiatus/backend/issues/84)

2020-09-30 10:05 UTC, amiskov requested changes
All looks good for me, there are just a couple of suggestions.

2020-09-30 10:05 UTC, amiskov commented on lib/cambiatus/kyc/kyc_data.ex
> +
There are 2 extra lines, they're unnecessary.

2020-09-30 10:05 UTC, amiskov commented on lib/cambiatus/kyc/kyc_data.ex
> +    |> foreign_key_constraint(:country_id)
My suggestion here is to move these `foreign_key_constraint` up and place them right after `cast(...)` like it's done in `address.ex`. Functions in this pipe are run one-after-another and if there are any constrain violation then we don't need any validation at all.

2020-09-30 10:12 UTC, amiskov commented on lib/cambiatus/kyc/kyc_data.ex
> +
BTW, you can run `mix format lib/cambiatus/kyc/kyc_data.ex` to get rid of any formatting issues. In VSCode there's also an option to format files automatically on save:

![image](https://user-images.githubusercontent.com/140053/94672756-60a10680-031e-11eb-9f20-f9ac11fc6db2.png)

2020-09-30 20:23 UTC, closed without merging

2020-09-30 20:55 UTC, victorgdev commented
Please refer to [PR#88](https://github.com/cambiatus/backend/pull/88)

2020-09-30 20:56 UTC, RodrigoLeiteF commented on .gitignore
> -# App artifacts
We need this file

2020-09-30 20:56 UTC, RodrigoLeiteF commented on config/dev.exs
> -use Mix.Config
This one too

2020-09-30 20:56 UTC, RodrigoLeiteF commented on config/test.exs
> -use Mix.Config
And this one