Adds proper error reporting to Auth.get_invitation
cambiatus/backend pull request #91
Opened 2020-10-05 18:19 UTC by RodrigoLeiteF

----

## What issue does this PR close
Closes #86

## Changes Proposed ( a list of new changes introduced by this PR)
1. Changes `invitation` query to return proper error messages

## How to test ( a list of instructions on how to test this PR)
1. Send an `invitation` query with a non-existing invitation ID

2020-10-09 08:56 UTC, amiskov requested changes
To test invitations with the frontend accepting responses properly we need precisions in the backend (they're added by @lucca65 in #90 but not merged in `master` yet). I think it's reasonable to review/merge #90 into `master` first, then update this branch from `master` and then finish the tests and the review.

2020-10-09 23:48 UTC, lucca65 commented on test/cambiatus/auth/auth_test.exs
> +      assert res == {:error, "Something went wrong while decoding the hashid"}
+1. Will you be able to fix this @RodrigoLeiteF ?

2020-10-13 21:31 UTC, lucca65 approved these changes

2020-10-14 10:04 UTC, amiskov approved these changes

2020-10-14 10:49 UTC, merged