Error msg improvements + KYC mutations refactoring
cambiatus/backend pull request #97
Opened 2020-10-13 19:32 UTC by victorgdev

## What issue does this PR close
Closes #84 

## Changes Proposed ( a list of new changes introduced by this PR)
For easier frontend error message consumption improved:
- Error message text from kyc changeset validation functions
- Delete_kyc and delete_address mutations and its error messages text

## How to test ( a list of instructions on how to test this PR)
Run mix phx.server command
Open http://localhost:4000/api/graphiql
Run the mutations listed below changing their input fields to reproduce the error messages.

- upsertKyc
- upsertAddress
- deleteKyc
- deleteAddress

## Mutation Examples For Testing

Wrong input fields examples for testing

- accountId: "victorgdev1" (non-existent account example)
- document: "11111111b" (invalid document entry example)
- documentType: "cedula" (invalid document_type example)
- phone: "4443333b" (invalid phone entry example)
- userType: "natura" (invalid user_type example)
- countryId: "b" (invalid country_id example)
- cityId:"1b"
- stateId: "1b"
- neighborhoodId: "1b"
- zip: "10101b"

No Error Mutation Run

```
mutation {
   upsertKyc(
      input: 
         {  accountId: "victorgdev11"
            countryId: "1"
            document: "111111111"
            documentType: "cedula_de_identidad"
            phone: "44433333"
            userType: "natural"
         })
  	{
    	document
    	documentType
    	isVerified
    	phone
    	userType
  	}
}

mutation {
   upsertAddress(
      input: 
         {  accountId: "victorgdev11"
            countryId:"1"
            cityId:"1"
            stateId: "1"
            neighborhoodId: "1"
            street: "Elm Street"
            number:"1"
            zip: "10101"
         })
         {
	 zip
         }
}

mutation {
   deleteKyc(
      input: 
    { account: "victorgdev11" })
    {
    reason
    status
    }
}

mutation {
   deleteKyc(
      input: 
    { account: "victorgdev11" })
    {
    reason
    status
    }
}

```

2020-10-14 15:37 UTC, lucca65 requested changes
The format looks weird, can you run `mix format` on those files?

2020-10-14 19:36 UTC, victorgdev commented
> The format looks weird, can you run `mix format` on those files?

I know felt the same, I did run the mix format command before commit and now again, file remains the same. My IDE uses the elixir-ls extension with formatting on save setup, which supposedly follows mix format guidelines. Is there any setup I need to do?

Screenshot after mix format
![image](https://user-images.githubusercontent.com/53874965/96036513-966fe000-0e32-11eb-989f-e21ff72330f0.png)

2020-10-15 22:17 UTC, lucca65 approved these changes

2020-10-22 12:21 UTC, amiskov approved these changes

2020-10-23 17:50 UTC, merged